### ISSUE TITLE
Add support for optionally making the popup appear on text input fields (ex: forms)

### ISSUE THREAD

**Issue by CanisLupus** [CanisLupus/swift-selection-search#10]
User T-Halen asked (in issue #1):
"Is there a way to set a preference for allowing a search on selected text in a FORM field?"

Firefox simply does not trigger the text selection event when text is selected in a form or Google's search bar, for example, so SSS isn't able to show the popup there (or even to search using "Search with" in the context menu).

To fix this, we would have to detect the text selection ourselves, probably by detecting all mouse release events and maybe some keyboard ones too (because you can select text by holding shift and pressing left/right in a page) and get the current selection at that point in time.

After that, I could add options to work on forms, or simply allow the context menu to work. While we're on that, I believe that I could fix the context menu in forms without removing the default selection detection.

**Comment by CanisLupus** [comment]
I've added support for the context menu search in forms and other input fields. The rest I don't think it's possible without re-doing the entire text selection to not use Firefox's stuff.

**Comment by T-Halen** [comment]
Hi, thanks for taking the time to consider my request, and implement the change!

The context menu searching appears to work as expected, much thanks!

Now if we could get rid of the disabled engines from the list. :-)

**Comment by CanisLupus** [comment]
You're welcome! Haha, the funny thing is that that is easy to implement, I just never thought to filter the context menu. It is a more "hidden" option and I thought you would like to see all search engines there.

I can add an option to use the same filter for the context menu. :) I'll note it down for later.

**Comment by CanisLupus** [comment]
Hello again! I've updated SSS with an additional option to show the same engines in the popup panel AND the context menu. :) It's near the bottom of the preferences page. It's part of my updates for version 2.13.3, so you can either grab the xpi file in the "build" folder or wait for Mozilla's review.

I'll close this issue, but if you have any issue feel free to write here. :)

Cheers,
Daniel
