### ISSUE TITLE
Problem with site search engine

### ISSUE THREAD

**Issue by peter099** [CanisLupus/swift-selection-search#104]
I imported the search engines from my firefox profile, but i found one site on which the search doesn't work, instead it redirects the search to google. This is how the site search is imported: `http://www.metal-archives.com/search?searchString={searchTerms}`

Any idea why it doesn't work?

**Comment by CanisLupus** [comment]
Hey Peter, sorry for the delay!

That is actually the website's choice. If you search normally in that site you'll see that it adds "&type=band_name" at the end of the URL (you can actually search for albums or songs too, using advanced search). However, if you remove this part of the URL, like you did, the site seems to think you want a more general search and redirects to Google instead.

It's just the way the site works. :)

I hope this helps.

Cheers,
Daniel

**Comment by peter099** [comment]
Thanks!

**Comment by CanisLupus** [comment]
You're welcome!
