### ISSUE TITLE
Separators don't work in the context menu.

### ISSUE THREAD

**Issue by defrilitus** [CanisLupus/swift-selection-search#109]
Neither do "Copy to clipboard" and "Open as link".
Not very important, so this is just an FYI ;-)

**Comment by CanisLupus** [comment]
Hey, thanks for the heads up but these are actually already mentioned in issue #99 and #84 respectively, if you want to see what I wrote. :)

So I'm closing this but neither one is forgotten!

Cheers,
Daniel

**Comment by defrilitus** [comment]
Daniel,
    
    I just saw the new version (3.26.1). Cool 😎
    Thanks for letting me know,
    
    Alessandro
    
      
        
          
        
        
          To: CanisLupus/swift-selection-search
          <swift-selection-search@noreply.github.com>
          CC: Defrilitus <alessandro@fontana.io>, Author
          <author@noreply.github.com>
