### ISSUE TITLE
Add option per-engine to automatically add quotes around multi-word searches

### ISSUE THREAD

**Issue by CanisLupus** [CanisLupus/swift-selection-search#112]
As suggested in the original issue #107 by @defrilitus:

> Is it feasible to add an option whereby the search term is automatically sent the search engine enclosed in quotes if there is a space in the search term (e.g., "John Doe")?

It can't be a global option (same for every engine) because some sites simply won't deal with the forced quotes in the same way as for example Google, which tries to get queries that exactly match the quotes.

It would need to exist as an option per search engine, which requires customizable per engine options.

**Comment by defrilitus** [comment]
Daniel,
    
    You are absolutely right. I've tried adopting your suggestion and it
    works correctly. Apologies, I should have thought of that!
    And thank you for continuing to work on SSS, which is already
    extremely impressive.
    
    Cheers,
    
    Alessandro
    
      
        
          
        
        
          To: CanisLupus/swift-selection-search
          <swift-selection-search@noreply.github.com>
          CC: Defrilitus <alessandro@fontana.io>, Mention
          <mention@noreply.github.com>

**Comment by CanisLupus** [comment]
No apologies necessary at all! :) I hadn't even remembered this either. I'm happy that it works for you. I'll be closing this issue then. :) Cheers!

**Comment by defrilitus** [comment]
Sorry, I hadn't realised that replying directly via e-mail would cause such a mess on GitHub. Next time I'll answer here ;-)
