### ISSUE TITLE
Pinterest?

### ISSUE THREAD

**Issue by ttggzz** [CanisLupus/swift-selection-search#115]
Hi, is there a way to have Pinterest as a context search engine with this, search all of Pinterest _without being logged in_? thank you

**Comment by CanisLupus** [comment]
Hey, I have never used Pinterest, so I'm not sure if this is what you are looking for, but you should be able to add the engine's search URL as `https://www.pinterest.com/search/pins/?q={searchTerms}` in the options page.

Does that help? :)

Daniel

**Comment by ttggzz** [comment]
Thanks, I put that link in and it did what was happening before: it goes to the pinterest web page but does not execute the search of the previously highlighted word. I use google image search heavily and quite often find myself at pinterest from links on the GI page. Wanted to try being able to search pinterest by choice automatically from the context menu. thanks for trying!

**Comment by CanisLupus** [comment]
Hmm it seems to work on my side. What I mean is that searching for random words from your last reply (link, google, pinterest) using that Search URL gives me the following pages:

Link
https://www.pinterest.com/search/pins/?q=link
![image](https://user-images.githubusercontent.com/532708/45384396-dd60cb00-b605-11e8-8224-9ddd217e9225.png)

Google
https://www.pinterest.com/search/pins/?q=google
![image](https://user-images.githubusercontent.com/532708/45384402-e18ce880-b605-11e8-9c11-88f7f80e76b6.png)

Pinterest
https://www.pinterest.com/search/pins/?q=pinterest
![image](https://user-images.githubusercontent.com/532708/45384416-eb165080-b605-11e8-817e-505efc14ab25.png)

Is this different from what happens on your side? Maybe I'm not understanding something.

Daniel

**Comment by ttggzz** [comment]
heh, those look... very good. Except I don't understand the results in the first one, how that is relevant to "link". Anyway, I'll have to look how I'm using that Pinterest link you provided, I probably have it set up wrong. When I just searched "highlighted", it just goes to the Pinterest page and says "search terms" at the top, not "highlighted". I have a bunch of long term accumulated problems with firefox that I'm working on resolving, could be related. thanks for getting back to me

**Comment by CanisLupus** [comment]
Ah, don't worry, Link is just the name of the main character in The Legend of Zelda videogames. :)

What is the URL when you get the "search terms"? Maybe the {searchTerms} of the Search URL is not written correctly.

I've added Pinterest to a default install of SSS so you can see how I'm doing it and compare. Maybe this helps:
![image](https://user-images.githubusercontent.com/532708/45386307-f455ec00-b60a-11e8-9db4-322a800900c7.png)

If everything is correct then I'm not sure what is going on, especially since there are no logins involved. But I would suggest disabling all add-ons and test, if that's the case.

Daniel

**Comment by ttggzz** [comment]
heh, Zelda :) 
url I'm taken to:
https://www.pinterest.com/search/pins/?q=%7BsearchTerms%7D
testing again from the word "worry"
https://www.pinterest.com/search/pins/?q=%7BsearchTerms%7D

Somehow I ended up with this in my setup, strange as I thought I was copy/pasting:
https://www.pinterest.com/search/pins/?q=%7BsearchTerms%7D
compared to what you originally posted:
https://www.pinterest.com/search/pins/?q={searchTerms}
changed it over, just searched "name"... VOILA! url:
https://www.pinterest.com/search/pins/?q=name

Excellent, this is wonderful! Didn't even need to restart Firefox! thanks for your help!

**Comment by CanisLupus** [comment]
Ah-ha! Good news, then. :) Strange that it was copied like that; something seems to have escaped the { and }.

Glad I could help. ;) Cheers!
