### ISSUE TITLE
[Workaround] : Youtube hidden in popup

### ISSUE THREAD

**Issue by Wassss** [CanisLupus/swift-selection-search#121]
> > Firefox 63.0.1
> > Swift Selection Search 3.27.2
> > uBlock Origin 1.17.2
> > Fanboy’s Annoyance List

This worked for me.
rename youtube search with something else, exp: YouTub
![yt](https://user-images.githubusercontent.com/7213383/47953079-79f57880-df78-11e8-99b4-e463137417e4.png)

**Comment by CanisLupus** [comment]
Hey, I think I remember someone doing this before we knew that the ad blocker list was the culprit. :) I'll try adding this info to the troubleshooting section of SSS's options page in case someone doesn't want to disable the list entirely.

This is not really an "issue", but I'll keep it open until I do that. ;)

Thanks!
Daniel

**Comment by CanisLupus** [comment]
I added a note in the Instructions section for version 3.28.0 (soon available) that YouTube can also be renamed to something else to avoid the problem. Thank you for suggesting the workaround. I will close this issue now. :)

Cheers!
Daniel
