### ISSUE TITLE
Icons missing in popup on delta.com

### ISSUE THREAD

**Issue by T-Halen** [CanisLupus/swift-selection-search#126]
https://www.delta.com/
Double click to highlight a word or phrase, and all icons in the popup are missing. (for me)
The links still work, but the icons are mssing.

**Comment by CanisLupus** [comment]
Hi T-Halen! Hmm... in that page they are visible for me but I have seen at least a website (don't remember which) where that happened. Is it possible that you have some ad-blocker or addon influencing this?

**Comment by T-Halen** [comment]
I disabled all addons except SSS, and still no luck.  Screrenshot:
[https://i.postimg.cc/bN9xtQGT/delta.jpg](url)

**Comment by CanisLupus** [comment]
Does this only happen to search engines and not to the "Copy to clipboard" or "Open as link" icons?

Here it works even if I disable all other addons (in case something was having the weird effect of making icons appear ;p).

Is there anything particular about the icons your engines use? If you try any other image from the internet as an icon, does it show?

**Comment by T-Halen** [comment]
Copy to Clipboard is one of my items, still missing the icon.  Out of the 7 other search engines, 5 have icons stored locally, and 2 are from the Internet.  Still missing all the icons.

I can't think of anything that might be blocking just delta.com

**Comment by T-Halen** [comment]
Think we can get anyone else with SSS installed to take a look at delta.com to see what their display is like?

**Comment by ZIEXED** [comment]
No problem here

**Comment by CanisLupus** [comment]
Thanks for checking, @ZIEXED. :) I also got some people to test this and they said it was working normally. Really weird. I'm having no ideas right now.

**Comment by T-Halen** [comment]
If it helps, the icons are fine on:
https://news.delta.com/
https://pro.delta.com/
https://www.deltajobs.net/

**Comment by CanisLupus** [comment]
Sadly I have no way of reproducing this to find the reason behind it. I have tried on a Firefox as old as version 52 (oldest supported by SSS) to see if it made a difference, but it still worked.

**Comment by CanisLupus** [comment]
Hey @T-Halen, did this issue ever magically solve itself or is it still happening? SSS version 3.40.2 changed a few things that could in theory affect this (Shadow DOM and changing request headers), but since it was never happening for me I'm not sure. :|

**Comment by T-Halen** [comment]
Yes, this issue is fixed in Version 3.40.2.  Thanks.

**Comment by CanisLupus** [comment]
Cool, thanks for confirming!
