### ISSUE TITLE
Use current URL as search term

### ISSUE THREAD

**Issue by AdKiller** [CanisLupus/swift-selection-search#128]
Is there any way to use the complete URL of current site as a search term?

**Comment by CanisLupus** [comment]
Hmm... Not exactly.

SSS supports {hostname}, which is the current domain (here, github.com), but not the complete URL. For {hostname} I include an example as `https://www.google.com/search?q={searchTerms} site:{hostname}` in the default search engines.

Is the full URL something you'd like as an option?

Daniel

**Comment by AdKiller** [comment]
Yes please full URL would be great. I moved to your addon because it handles favicons much better than Selection Context Search by ContainersOnTheGo, that addon can do this.

**Comment by CanisLupus** [comment]
I'll add this to my to-do list. ;)

Just to be clear, you'd like support for something like `{url}` that you could add to any search engine (just like `{hostname}`), where `{url}` gets replaced with the current URL. Using this issue's URL as an example, `{url}` would become `https://github.com/CanisLupus/swift-selection-search/issues/128`. Is this correct?

**Comment by AdKiller** [comment]
yes exactly. thanks

**Comment by CanisLupus** [comment]
Hey there!

SSS version 3.29.2 now supports {href} if you want to add the current full URL to a search. I went ahead and also implemented everything that the JavaScript URL object provides (for specific parts of the URL; not only all of it), so you can use:

{hash}, {host}, {hostname}, {href}, {origin}, {password}, {pathname}, {port}, {protocol}, {search} and {username}. Everything is documented [here](https://developer.mozilla.org/docs/Web/API/URL#Properties).

Please let me know if there are any problems.

Happy holidays! :)
Daniel

**Comment by AdKiller** [comment]
works great! thanks a lot. happy new year!

**Comment by CanisLupus** [comment]
You're welcome! Thank you and have a happy new year as well! :)
