### ISSUE TITLE
Google Docs 

### ISSUE THREAD

**Issue by gaucho2005** [CanisLupus/swift-selection-search#131]
The add on doesnt work on several things, most importantly google docs

**Comment by CanisLupus** [comment]
Hello! You didn't give me a lot of information, so here are multiple things:

1. If you didn't do this already, remember that for the SSS popup to work on editable text fields you need to turn on the option "Allow popup on editable fields" under "Popup/icons behaviour". However, if you use the context menu and not the popup it should work regardless of this option.
2. SSS works on Google Sheets and probably some other types of docs, but unfortunately not on the contents of a Google Doc, as you mention. It seems that Firefox itself cannot detect text selections in Google Docs.

    For example, select some text in the doc and right click it. Google overrides the context menu, so you will only see the doc's custom context menu. But even if you click outside the working area of the document to show Firefox's context menu you should see that there's no context menu entry for "Search Google for <something>" entry (replace "Google" with your default search engine). This appears when there's text selected but not even Firefox detects it. :(

    I'm guessing that Google implements the content of a Google Doc as something that is not normal HTML text, and overrides/disables some other things via JavaScript. I'm not sure if I can work around this, but I can have a look in the future.

3. Lastly, you mention it doesn't work on other places besides Google Docs. Can you tell me which so I can see?

Thanks for the report. :)

Cheers,
Daniel
