### ISSUE TITLE
Searc engine list directly in context menu

### ISSUE THREAD

**Issue by fabeit** [CanisLupus/swift-selection-search#133]
Is it possible to have the search engines listed directly in the context menu and not in the add-on submenu? That reduces the time it takes to navigate to the SSS sub-menu.

Thanks!

**Comment by CanisLupus** [comment]
Hi! Unfortunately as far as I know it's not possible. :( This was requested by several people but I don't think there's much I can do.

Please see [this other (closed) issue](https://github.com/CanisLupus/swift-selection-search/issues/129) for more details.

Cheers!
Daniel

**Comment by fabeit** [comment]
Thanks for the reply, too bad. It seems strange that such a customizable browser doesn't allow such simple hack.

**Comment by CanisLupus** [comment]
True. Firefox add-ons stopped being able to do some things when the transition to WebExtensions happened. Some restrictions are for the best; others seem unnecessary. I think this falls in the latter group...

**Comment by fabeit** [comment]
I am actually using Waterfox, so maybe there is a way to do this?

**Comment by CanisLupus** [comment]
I wish I could say yes, but it's also a no. The limitation here is that SSS is a WebExtension since a few years ago (it was either that or disappear), so even on Waterfox it is still a WebExtension and so it can't do this. :(
