### ISSUE TITLE
Yippy

### ISSUE THREAD

**Issue by David1501** [CanisLupus/swift-selection-search#134]
Ciao! Any idea on how to add Yippy? tried various options without luck....

**Comment by CanisLupus** [comment]
Hi David,

To be honest, no idea. :) The site seems to generate a token for your session, which is common practice in cookies, but I don't know why they also use the URL for this. It seems that searches without a valid token don't work.

You may have done this already but you could use the following and replace [your token here] with the token the site gave you, but it would only be valid until the token expires, and probably only in the same browser:
https://yippy.com/search/?v%3Aproject=clusty-new&query={searchTerms}&xtoken=[your token here]

Not helpful... So I don't have a solution, sorry.

Daniel

**Comment by David1501** [comment]
Ah ! Ok Thank you for the answer...I thought it was me makin somethin wrong!! :-) Thank you very Much!

D.

**Comment by CanisLupus** [comment]
You are welcome! ;)

I'm closing this issue since I don't think there's much that can be done to fix this, unless there are other ways to use Yippy that don't need the token.
