### ISSUE TITLE
remove FF's search item from context menu?

### ISSUE THREAD

**Issue by rmlrml** [CanisLupus/swift-selection-search#137]
Thanks for this, the best context search addon there is.

Sorry if I missed it, but is it possible to hide FF's "Search [default search engine] for [selected text]" item from the context menu?  I didn't catch any such option in FF preferences, about:config, or SSS preferences.  Since I have the SSS sub-menu and I never use this built-in context menu search item, I figure why not hide it.

**Comment by CanisLupus** [comment]
Hello there! Thank you for the compliment, I'm glad you like it. :)

Hiding other context menu items (either the browser's or other extensions') is not possible for an addon but, via manual changes by a user, a way to do this (maybe the only way) is to change/create the userChrome.css file and hide that option. 

(Steps adapted from comments [here](https://www.reddit.com/r/firefox/comments/9eteoj/help_how_to_edit_context_menu/e5rispn/) and [here](https://www.reddit.com/r/firefox/comments/a9qs9a/how_to_remove_search_google_for_in_the_context/).)

1. Enter `about:profiles` in the URL.
2. Click "Open Folder" next to the Root Directory of your profile.
3. In this folder, create a folder named "chrome".
4. In it, create a file named "userChrome.css".
5. Add this to the file:
```
#context-searchselect {
	display: none !important;
}
```
6. Restart Firefox.

The default search option should be gone. The userChrome.css file lets you edit some things using CSS. #context-searchselect is just one of them. The first link contains more as examples.

Please let me know if this helps. It worked for me.

Daniel

**Comment by rmlrml** [comment]
Sorry for the delayed response.  Worked perfectly, thanks!

**Comment by CanisLupus** [comment]
No problem. Great, you're welcome!
