### ISSUE TITLE
(random issue) YouTube icon doesn't show up in panel, even if selected in settings (icon is hidden)

### ISSUE THREAD

**Issue by CanisLupus** [CanisLupus/swift-selection-search#14]
Title. Quoting from user Alex's review of SSS:

> For some reason, Youtube search doesn't show up in menu, even it's selected in settings. I mean the first one, which is original:
> http://i.imgur.com/8UC4yZF.png
> http://i.imgur.com/rBZ1b2W.png

**Comment by CanisLupus** [comment]
Quoting from my own answer, to get everything under this issue:
> Let's see if I got this right:
> 
> You have two search engines for YT set in Firefox, one of which comes with Firefox (the one that does not work) and another one. Is this correct?
> 
> If you go to youtube.com does Firefox let you add a new search engine to the search bar? (probably not if it is original and from YT, but just to be sure). I ask this because the YT search I use on my Firefox also came with the browser but the icon is the newer YT "red play button", so it could be an older version.
> 
> But even if that was the case, the search engine should appear in the panel. I see from your images that the panel is getting the correct width for 5 icons but only showing 4. I'll look into this.

**Comment by AlexFundorin** [comment]
Hi, it's Alex. I'm using defauly НЕ search engine from Firefox. The other one was added just to try it as a substitute for a non-working engine. I'm using this one. http://i.imgur.com/VTm0C2E.png
Tried deleting and installing it from official site. Also tried restoring default search engines. Every other engine is usable and immediately shown it swift, after it was selected in the addon settings.

**Comment by AlexFundorin** [comment]
In fact, is somehow worked at one particular russian site today. http://i.imgur.com/vYTqnNl.png
I thought that you've fixed this issue, but every other site still doesn't show Youtube search engine in Swift. http://i.imgur.com/YfFlw5F.png

UPD. I've disabled ublock origin addon and Youtube appeared on pages, where ublock was disabled.

**Comment by CanisLupus** [comment]
Hi Alex,

1. I tried installing that add-on, which adds the YT icon, while also having uBlock Origin installed, and the icon was correctly displayed on my Firefox with uBlock active for every website. I couldn't reproduce the problem here. :(
2. Have you tried restarting Firefox? It could stay the same, but it's worth a shot.
3. I'm not sure if this is something I can fix, especially if turning uBlock on and off changes the behavior in SSS. But I don't understand why I didn't see that happen on my end...

If you have more information please share. :)

**Comment by AlexFundorin** [comment]
Hi. There was an issue with some custom blocking lists in ublock, which contained ##img[title="YouTube"] filtering lines. My list was "RUS: BitBlock List". I know that Fanboy's social list also have this filter. I just need to find a way of how to add YouTube icon to the exception list of ublock, and everything should work again.

**Comment by CanisLupus** [comment]
Okay, Alex, I'm glad that you can confirm that it was really being caused by uBlock filtering. :) On my end, the best I could probably do is try to make non-existent icons still occupy space in the popup (so they don't vanish and cause the popup to have more left and right padding.

I hope you figure out the filtering! :)

Cheers,
Daniel

**Comment by AlexFundorin** [comment]
Thanks. I've just disabled that particular filtering list. If you'll ever decide to use non-existing icons, you might use Gmail way. https://i.stack.imgur.com/ioQAK.png

**Comment by CanisLupus** [comment]
That's an idea, yes. :)

Happy new year!
