### ISSUE TITLE
No Donate section?

### ISSUE THREAD

**Issue by ry4n3** [CanisLupus/swift-selection-search#142]
**Describe the problem**
No donation spot when it is truly deserved, this addon is beautiful a very very helpful addition to what I do.

**Comment by CanisLupus** [comment]
Hello! Wow, thank you so much <3 :) Do you mean donations here on GitHub?

I do have a link to a PayPal contributions page on the addon's page [here](https://addons.mozilla.org/firefox/addon/swift-selection-search/) (on the left, the blue button "Contribute now"), for anyone that wants to buy me a beer (actually, probably cider :p).

Cheers!
Daniel

**Comment by CanisLupus** [comment]
You contributed! :D Thank youuuu, you're awesome ❤

PS: I'll close this "issue" soon :)
