### ISSUE TITLE
context search won't open in new tab

### ISSUE THREAD

**Issue by bowbowx** [CanisLupus/swift-selection-search#143]
when i highlight a text.. a search option context window open up.. in order version if i click the search engine, it would open a new tab.. but it doesn't do that anymore despite selecting the correct option in the option menu.. any fix?

**Comment by CanisLupus** [comment]
Hello!

I'm not sure if you are using the popup (the one that appears when you select text) or the context menu (the submenu when right clicking the page), but it works for me in both. Can you check if you are using the right option?

There are 2 settings under "Popup/icons behaviour" (for left and middle mouse click). These are for the _popup_ icons.
![image](https://user-images.githubusercontent.com/532708/59550397-35947700-8f62-11e9-8cd0-c0732c70e081.png)
![image](https://user-images.githubusercontent.com/532708/59550328-40024100-8f61-11e9-9453-47b578cb7f73.png)

However, if you are using the right click context menu, you should be using the option under "Context menu":
![image](https://user-images.githubusercontent.com/532708/59550401-3decb200-8f62-11e9-8bbf-a0f061d94aad.png)
![image](https://user-images.githubusercontent.com/532708/59550330-498ba900-8f61-11e9-8261-0f98684ae57b.png)

Please see if you are using the correct one and let me know. :)

Daniel

**Comment by CanisLupus** [comment]
Hey, I'm closing this issue since you haven't replied. :) If there are still problems please let me know when you can.

Daniel
