### ISSUE TITLE
Search on multiple search engines in one click

### ISSUE THREAD

**Issue by caryngh19** [CanisLupus/swift-selection-search#146]
Hi Daniel, 

I am current using Swift Selection and I really like the clean design and how easy it is to use.
Thanks for making this!

I think it will be great if you can make it possible to search on multiple search engines at one go. 
For example, selecting the phrase "blue bag" and searching on Amazon and Ebay (maybe add a "multiple search engine" option) in one go instead of clicking two times for two different search engines. 
I was previously using another add-on that had this feature and found it really helpful. 

Hopefully you can consider it for Swift Selection!

**Comment by CanisLupus** [comment]
Hi! :) I'm happy you like it. Thank you!

I believe what you are suggesting is the same as #72, and in fact I've also received a similar suggestion via email before. It seems this is important for quite a few people. :)

I already have it in my to-do list, but I haven't made a lot of progress in SSS recently. This feature and an optional search bar in the popup are probably the things I'd like to work on next, when I find the time to return to it. ;)

Cheers!
Daniel

**Comment by caryngh19** [comment]
Hi Daniel, 

My apologies for the repeated enhancement request, but glad to hear that there are others who are looking forward to this new feature too!
Thanks for developing this add-on and hope you will get the time to work on it soon!

**Comment by CanisLupus** [comment]
No problem at all! I'll be closing this issue eventually, since I have it noted down elsewhere and there's 72, but for now it stays open as a reminder.

You are welcome! Let's hope so. :)

**Comment by CanisLupus** [comment]
Hi @caryngh19, I've posted in #72 as well, but if you're still around here after more than a year I'm letting you know that SSS version 3.47.0 finally implements group engines. Please thank @igorofc for that. ;)

I'm closing this issue. Feel free to comment here or in 72 if you find any problems.

Cheers!
