### ISSUE TITLE
Stop adding http:// initial automatically before URI

### ISSUE THREAD

**Issue by mikelei8291** [CanisLupus/swift-selection-search#147]
**Describe the problem**
SSS will automatically add a `http://` initial for URIs without the double slash `//` after the scheme of them. As described in the [Generic syntax](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax) section of the wikipedia page of URI, the double slash is not a mandatory part of the "path".

Also, for example, I would like to pass the search term to the "[Everything](https://www.voidtools.com)" program by calling its URI `es:`. Adding a double slash after the colon will also add it before the search term in the search box of "Everything". Then I have to delete the double slash manually to perform a proper search, but call the URI directly with `es:{searchTerms}` won't have such a problem.

![Everything search](https://user-images.githubusercontent.com/9620335/62388446-ecd76280-b58f-11e9-814c-0f8c21ee79ab.png)

**How to reproduce the problem**
1. Go to "SSS Options"
2. Click on the input box of "Search URL"
3. Input "`es:{searchTerms}`" and unfocus the input box
4. The search URL automatically becomes "`http://es:{searchTerms}`" which won't call the "Everything" program by its URI

**System info:**
- Browser: Firefox
- Browser version: 69.0b5
- System: Windows 10
- Everything version: 1.4.1.935

**Comment by CanisLupus** [comment]
You're completely right! This can be easily fixed. I will try making an update soon. Related, I'd also like to do issue #86, from someone who also uses Everything, but that's much more time consuming.

Thanks for reporting. :)

Cheers!
Daniel

**Comment by CanisLupus** [comment]
SSS version 3.33.1 (already in the market) fixes this. Please let me know if it's working well for you and we should be able to close this. :)

**Comment by mikelei8291** [comment]
Yes, it works perfectly. Thanks for your great work!
Sorry for the late reply, I was not able to use my computer for the past few days.
Also for issue #86, one possible solution is using `location.href = "{searchURL}"` to open these URI that will invoke a third-party program. However, this won't work for normal search URLs, as this will rather open the search page on the same tab (but this may just be the intended behaviour?).

**Comment by CanisLupus** [comment]
Glad I could help. :) It wasn't behaving as intended.

No problem at all!

Yeah, I believe it should do that. That issue would likely require a custom solution like a setting that is configurable per search engine.

Cheers!
