### ISSUE TITLE
Allow selecting which search engines appear in the context menu flyout

### ISSUE THREAD

**Issue by Gitoffthelawn** [CanisLupus/swift-selection-search#15]
Would be nice, but hardly a big issue.  If you have time... if not, no worries... :)

Personally, I don't use the context menu very often.

**Comment by CanisLupus** [comment]
:) Do you mean full customization? Two SSS versions back or so I added the possibility of filtering the context menu to use the same engines as the popup. That's not full customization, though. ;)

**Comment by Gitoffthelawn** [comment]
I generally prefer full customization where possible, but it's obviously easier to just have the ability to ignore specific search engines.

**Comment by CanisLupus** [comment]
OK, I'll write that down. It's no too hard because it's very similar to the selection for the popup itself, but I seriously have to consider another way to show the options. The auto-generated preferences page for SSS is a bit unwieldy now.

**Comment by Gitoffthelawn** [comment]
It's a bit unwieldy, but honestly, I prefer the power over the pretty for this tool.  As a UI/UX expert, I'm surprised to hear myself say that. :)

**Comment by CanisLupus** [comment]
I understand. :) It's not a page that you are constantly looking at, so it's not as important as a main UI, but right now what bothers me is the wasted vertical space, the lack of separators or categories, and the giant horizontal number fields that go like this:

[________________________________________________________________________________________________________24]

-.-

Well, someday...

**Comment by Gitoffthelawn** [comment]
I agree :)

**Comment by CanisLupus** [comment]
Hey there, @Gitoffthelawn! I hope everything is alright with you. :)

It has been more than a year and a half since your request (it's the oldest one still open!), but I've finally added checkboxes to choose which engines appear in the context menu hehe (version 3.26.1). It was part of a series of changes that will let SSS have configurable options per engine if necessary.

I'll be closing this issue now. ;)

Cheers,
Daniel

**Comment by Gitoffthelawn** [comment]
@CanisLupus Hi Daniel!  Things are good.  I hope things are well with you too! :)
