### ISSUE TITLE
[Feature Request] Dark Mode for settings page.

### ISSUE THREAD

**Issue by DeadNews** [CanisLupus/swift-selection-search#150]
That would be great.

**Comment by CanisLupus** [comment]
Hi and thanks for the suggestion! :)

**Comment by CanisLupus** [comment]
Hey @DeadNews, version 3.43.0 (now 3.43.2) adds dark mode to the options page. It's not exactly perfect, colors-wise, but I think it gets the job done. ;)

Cheers!
Daniel
