### ISSUE TITLE
autohotkey.com/docs/ never loads when SSS is enabled

### ISSUE THREAD

**Issue by frm1001xplrr** [CanisLupus/swift-selection-search#153]
Problem description:
I visited https://www.autohotkey.com/docs/AutoHotkey.htm but the left navigation pane never loads. 

1. Go to https://www.autohotkey.com/docs/AutoHotkey.htm
2. Observer loading animation forever in left navigation pane 
3. Disable SSS
4. Page loads instantly

System Info: 
- Browser:  Firefox 69
- Browser version: 69.0
- System: Windows 10 Pro x64

**Comment by CanisLupus** [comment]
Hey! Unfortunately (or fortunately :p) I cannot reproduce this. After opening the site, the side bar and everything else loads correctly for me, even with SSS on Auto opening behaviour.

I'm using the same exact versions on everything. I also tried on Firefox 52 (the oldest version supported by SSS) and it still loads the side bar there.

Could you please try disabling all other addons and see if the problem remains? It's strange that disabling SSS solves the problem for you, but it could also be some kind of incompatibility with another plugin.

Cheers!
Daniel

**Comment by frm1001xplrr** [comment]
Huh, site works now whether SSS is enabled or disabled...

I do apologize, I tested several times with the same result before opening this issue.

Bowing and closing issue right away :)

/f1x

**Comment by CanisLupus** [comment]
No problem at all! Glad to know everything is fine. ;)
