### ISSUE TITLE
I don't know where else to post this? Problem entering correct URL terms for search engines

### ISSUE THREAD

**Issue by marlboonyer** [CanisLupus/swift-selection-search#154]
I am trying to add some search engines particularly Google Images.
I have tried every combination of terms with no joy.
can you advise on correct terms?
thx

**Comment by ZIEXED** [comment]
`https://www.google.com/search?hl=en&site=imghp&tbm=isch&q={searchTerms}`

**Comment by CanisLupus** [comment]
Thanks, ZIEXED :) The link you posted works nicely. I believe it may be shortened to this (removing language and site=imghp), or at least this works for me as well:

https://www.google.com/search?tbm=isch&q={searchTerms}

I'm closing this issue unless something else comes up.
