### ISSUE TITLE
Text box below buttons

### ISSUE THREAD

**Issue by Smylers** [CanisLupus/swift-selection-search#159]
Hi. Thank you for the new text box that pops up in version 3.40.2. I'm wondering if it could be positioned under the search buttons, rather than above them?

I often have wanted to tweak a phrase I'm searching for, so the text box should be really useful. However, for most searches there isn't a need to adjust the text, and it's awkward that picking a search button now involves moving the mouse so much farther.

Previously having selected the search text, it was only necessary to nudge the pointer down a couple of pixels to the row of buttons:

![image](https://user-images.githubusercontent.com/598534/70040189-0545a100-15b3-11ea-8358-142205d94537.png)

Whereas now with the text box in the way, it has to travel several times the vertical distance to the buttons, making swift selection searches noticeably less swift:

![image](https://user-images.githubusercontent.com/598534/70039653-340f4780-15b2-11ea-8518-771fa191451b.png)

If the text needs adjusting, that's obviously going to involve more interaction and take longer anyway, so I don't think it matters if the text box is the item that's least convenient to get to.

So either moving the text box to the bottom, or an option for users to set whether it's bottom or top, would be appreciated.

Apologies if I should be able to do this myself with the new custom custom-CSS feature.

**Comment by CanisLupus** [comment]
Hello! This is a perfectly reasonable suggestion. :)

Out of curiosity, how are you placing the popup below the cursor? Negative popup offset? There was at least one user that requested an option to place the whole popup below the cursor instead of above. Maybe adding this and your suggestion would be a good match, when I have some time.

No need to apologize, it's definitely not my intention to force people to use CSS for the more "common" things that could have an option. It's probably possible, yes, but it may have conflicts with the internal formatting too.

**Comment by Smylers** [comment]
> Hello! This is a perfectly reasonable suggestion. :)

Thanks.

> Out of curiosity, how are you placing the popup below the cursor?

Oh, I hadn't realized I was doing anything special. I have ‘popup location’ set to ‘bottom right corner of selection “rectangle”’, and no negative numbers in any of the fields.

This is on Ubuntu, running the Mate desktop environment, if that is relevant.

Here's my settings:
[SSS settings backup (2019-12-03T21.09.11.143Z).json.txt](https://github.com/CanisLupus/swift-selection-search/files/3918729/SSS.settings.backup.2019-12-03T21.09.11.143Z.json.txt)

**Comment by CanisLupus** [comment]
Ah, don't worry, you're not doing anything out of the ordinary. :)

It's just that by default the popup appears above the cursor, and I didn't notice it was exactly below the selection so I thought it was negative offset (which is also a valid approach but would require changing the offset if the popup grows in size vertically).

For "bottom right corner of selection rectangle" the text box is indeed not very well positioned. ;)

**Comment by CanisLupus** [comment]
SSS version 3.41.0 added this option, right below the "Display text box" one. Please let me know of any problems. :) Cheers!
