### ISSUE TITLE
It's not straightforward adding search engines

### ISSUE THREAD

**Issue by marlboonyer** [CanisLupus/swift-selection-search#166]
Example: today I tried adding dictionary.com. 
I've tried variations in the list but none of them work. 
I either get a 404 error or just the site without search terms.
I've had this several times now and it's getting frustrating.
Am I missing something?
It's a very useful add-on but I don't want to have to deal with all effort..
thanks

**Comment by ZIEXED** [comment]
`https://www.dictionary.com/browse/{searchTerms}?s=t`

**Comment by CanisLupus** [comment]
As always, thank you, @ZIEXED ;)

Adding search engines is not always easy, but there's also not an easy way to do this automatically.

Even if it could be possible to make a dummy search automatically and try to see where in the URL (if at all) the dummy text appears, SSS would already need to know HOW to search on a certain website. It needs user intervention.

I know this is a problem for users, so I did what I could to explain how to do this in the Instructions section in the options page:

![image](https://user-images.githubusercontent.com/532708/71307046-c734e380-23e0-11ea-88a1-3262d529ad50.png)

Did you read this? I accept suggestions! :)

Cheers,
Daniel

**Comment by CanisLupus** [comment]
Closing due to no additional input!
