### ISSUE TITLE
Force show popup visible

### ISSUE THREAD

**Issue by Mike-Reddick** [CanisLupus/swift-selection-search#168]
some times when you select an text on extreme top of the site you can't see the popup because popup open out of visible area, need an setting to force show popup in visible area

**Comment by CanisLupus** [comment]
This happens when the page is not scrolled to the very top, since SSS tries to keep itself inside the page but not inside the viewport of the window. I'll look into this when I have some time. Happy new year! :)

**Comment by Mike-Reddick** [comment]
thanks the attention, and happy new year festivities to you also!

**Comment by CanisLupus** [comment]
Hey @Mike-Reddick, SSS version 3.41.1 finally fixes this (hopefully!). I couldn't find problems with it, but you never know...

Let me know if you still find that the popup is not fully visible in some situations.

Cheers!
Daniel

**Comment by Mike-Reddick** [comment]
Whats up @CanisLupus, I downloaded the last version today, and if needed I can post some feedback, but I my first tests seem very good. Thanks so much!

**Comment by CanisLupus** [comment]
Hey there! Ah, great. :) No need to do tests on purpose, but if you find something wrong in your normal usage (on any specific website), please let me know.

You're welcome!

Cheers,
Daniel
