### ISSUE TITLE
suwapatsahapong

### ISSUE THREAD

**Issue by one-hub** [CanisLupus/swift-selection-search#177]
**Describe the problem**
A clear description of what is happening and what should happen.

**How to reproduce the problem**

**Anything else you'd like to include**
What you tried already, screenshots, attachments, examples, etc.

**System info:**
- Browser: [e.g. Firefox, Waterfox, etc]
- Browser version: [e.g. 64]
- System: [e.g. Windows 10, macOS]

**Comment by CanisLupus** [comment]
Hello! I'm presuming that this issue was a mistake, so I'm closing it. Feel free to update it and reopen if needed. ;)
