### ISSUE TITLE
"Open as link" not working when the URL does not contain a fully valid URL (i.e. including protocol)

### ISSUE THREAD

**Issue by CanisLupus** [CanisLupus/swift-selection-search#18]
Quoting user Gitoffthelawn (on issue #5):
> For example, the first 3 examples on this page will work, but the last 3 will not:
> https://github.com/Gitoffthelawn/HTMLtest

NOTE: I thought it was working before (previous Firefox version), but not sure. Will investigate.

**Comment by vurtomatic** [comment]
Hi! I'm on Firefox Nightly running the latest version of your addon. I'm writing to confirm the last 3 URLs (www.example.com, example.com, example.org) don't work.

This is the error in the newly opened tab:
```

File not found

Firefox can’t find the file at moz-extension://9d847ed4-ece2-3c4d-a0ad-ee26ae3b2b80/www.example.com.
```

**Comment by CanisLupus** [comment]
Submitted v3.3.0 to AMO including a fix for this (finally!) ;) It was such a simple thing, too. If I had ignored all the demoralizing work to support WebExtensions this would have been done a loooong time ago hehe.

Thank you for reminding me, @vurtomatic, and thank you for the very helpful HTMLtest page, @Gitoffthelawn.

I'll close the issue, but please feel free to reply if the problem persists in some weird case after updating.
