### ISSUE TITLE
Sharing "locationHref" to Telegram

### ISSUE THREAD

**Issue by mortyobnoxious** [CanisLupus/swift-selection-search#182]
Hi, I know this is a very specific request but is it possible to add an option to get `window.location.href`.

For example instead of:
`tg://msg_url?url={searchTerms}`
it will be
`tg://msg_url?url={locationHref}`

For now I use `tg://msg_url?url={searchTerms}` and paste URL into input field myself and it works but getting locationHref as variable would be great.
![image](https://user-images.githubusercontent.com/42044258/75118452-5aadbd80-568b-11ea-8599-18e3f84ccc7a.png)

Another use case for this could be opening URL with a proxy, for example
`https://proxy.duckduckgo.com/iu/?u=https://i.imgur.com/AD3MbBi.jpg`

It's still very specific :) but it would be great if you consider.

**Comment by mortyobnoxious** [comment]
Oh, sorry it already exists. :D

https://github.com/CanisLupus/swift-selection-search/issues/128

**Comment by CanisLupus** [comment]
Haha seems like you found it! :) A mention of those is hidden away in the "Advanced usage" section of SSS's instructions at the top of the options page.

**Comment by mortyobnoxious** [comment]
Wow there's a lot of options there.

**Comment by CanisLupus** [comment]
Yup. ;) Although most of the "Advanced usage" section exists to (try to) explain the possible modifications to "searchTerms".

**Comment by mortyobnoxious** [comment]
Hi, since this is a trivia question, I decided to ask it here instead of opening a new issue.

Is there a way to extract tweet id from "locationhref"? I tried but couldn't manage.

For example, this is URL:
`https://twitter.com/BernieSanders/status/1233962400556122112`

I wanted to extract `1233962400556122112` this part. Is it possible?

@CanisLupus

**Comment by CanisLupus** [comment]
Hmm... unfortunately no. You have ways to get the URL's protocol, domain, path to the page, etc, but not a part of the path to the page.

I could leverage the existing searchTerms code to allow replacements and other modifications on the JavaScript properties as well. I've added it as a TODO on my end. :)

**Comment by mortyobnoxious** [comment]
Thank you.

**Comment by CanisLupus** [comment]
Hey @mortyobnoxious, in version 3.41.1 (just updated) I added support for modifications on the URL variables. In general, you can use {href{replace_this|with_this}}, but URLs like `https://twitter.com/BernieSanders/status/1233962400556122112` are different every time, so we need to use regular expressions (not sure if you are familiar with those at all) to try and remove everything that is not the number/ID.

So to filter out `1233962400556122112` from an href like `https://twitter.com/BernieSanders/status/1233962400556122112` you could use (sorry, this is ugly xD):

	{href{re/[^\d]+/g|}}

In practice:

	     {re/[^\d]+/g  	// match anything that is NOT a number...
	                 |} 	// and replace it with nothing

However, if the username "BernieSanders" was "B3rni3S4nd3rs", you'd get _3343_1233962400556122112, so we need something better (i.e. even uglier) like this:

	{href{re/.+\/status\/(\d+).+/|$1}}

It basically matches all possible characters with `.+`, then `/status/`, then a sequence of digits with `\d+`, and then finally anything irrelevant that might come after in the URL with `.+` again. Then it replaces ALL of that with just the thing we placed in parenthesis, which is the number given by `(\d+)`.

**Comment by mortyobnoxious** [comment]
Thank you so much. 

This is also a great simple regex lesson for me :) I'm going to learn some regex, it's seems so much useful.

**Comment by CanisLupus** [comment]
Glad I could help. :)

Regex is very useful in some situations, though it can be hard to visually parse! The rules are mostly simple, however. I think it's a useful skill. :)
