### ISSUE TITLE
popup not working on wired.com?

### ISSUE THREAD

**Issue by isanynameavailable** [CanisLupus/swift-selection-search#186]
That's it -- popup works on other sites, but not on www.wired.com, however SSS is still in the context menu

**Comment by ZIEXED** [comment]
Works fine here.

**Comment by isanynameavailable** [comment]
Thanks for your quick response.

The following Firefox add-ons were responsible for the behaviour:

	Decentraleyes
	Greasemonkey: Don’t Fuck With Paste
	uBlock Origin: haven’t determined which filter list is responsible yet

Funnily enough, or perhaps not, the pop-up works on www.wired.co.uk <http://www.wired.co.uk/> with all these enabled.


	Regards,

	Simon

**Comment by CanisLupus** [comment]
Hey @isanynameavailable, I thought this was actually going to be about a bug that I introduced in the previous version (that I've since fixed it for version 3.41.2), but it doesn't seem that way.

On my end it's always working, but I have different addons, though I do use uBlock Origin.

Out of curiosity, do you mean that all of those extensions make the popup stop appearing?

Cheers,
Daniel

**Comment by isanynameavailable** [comment]
Daniel,
	What I did was to disable all the add-ons that block scripts/trackers, etc and then enabled them one by one whilst checking SSS’s pop-up on https://www.wired.com. Decentraleyes and Don’t Fuck With Paste both prevented the pop-up when enabled, as did uBlock Origin (UBO), or at least UBO seemed to prevent the pop-up from appearing, but I later enabled it again on wired.com <http://wired.com/> and, lo and behold, the SSS pop-up still worked, so I’m not sure what to say about that. At the moment I’m running with Decentraleyes, Don’t F*ck... disabled and UBO enabled, but I have to make sure that all scripts for wired.com <http://wired.com/> and www.wired.com <http://www.wired.com/> are enabled in UBO. This is new behaviour, I didn’t have to modify the add-ons previously. Maybe it’s due to the SSS update, but there was also a Bypass Paywalls update recently, so it could also be due to that, maybe?


	Cheers,

	Simon

**Comment by CanisLupus** [comment]
Hello Simon,

I don't think the SSS update could have caused this, but the problem should now be fixed in any case,

On my end I installed all 3 addons you mentioned (I already used uBlock Origin) and left everything at their defaults, and SSS still showed up as normal, so I believe this may be something related to some configurations of those addons (or the browser) on your end.

I'm curious as to what is causing this, though.

**Comment by isanynameavailable** [comment]
Daniel,
	Thanks for getting back in touch. Whilst I did observe the behaviour I described with the add-ons I mentioned, when I revisited wired.com <http://wired.com/> I found that disabling them had not resolved the problem I was having. In fact wired.com <http://wired.com/> would not load at all — the page appeared briefly, then disappeared, leaving a white screen. I think the difference between my initial investigation with the add-ons and then later accessing the site was due to my having simply reloaded wired.com <http://wired.com/> in an open tab whilst disabling/enabling the add-ons versus opening the site in a new tab. I don’t know enough about Firefox to understand the behind-the-scenes difference between the two.
	So, this is what I eventually found out: it was a setting in Trace that caused all my issues. Once I whitelisted wired.com <http://wired.com/> in Trace and clicked on “Hardware Fingerprinting Protection” (to turn the entry black — I’m still not sure if this enables, or disables the specific protection because the add-onn is not very self-explanatory on that point), so that it was the only protection that was black in the list of options for the site, my problems with wired.com <http://wired.com/> went away — the site loads just fine and your excellent add-on also works just as you intended.

	Sorry to have misled you in my previous email, but I think I have the issue identified and sorted now. Just checked again: uBlock Origin, Don’t f*ck… and Decentraleyes all enabled, Trace modified as described above — all is as it should be!


	Happy physical distancing!

	Simon

**Comment by CanisLupus** [comment]
Ahhh, no problem! Mistakes happen. I'm glad you sorted out the problem and get to keep that addons playing nice with each other. In that case I'll close this issue.

Happy physical distancing to you as well. ;) Stay safe.
