### ISSUE TITLE
Allow users to change the default Icon URL, to avoid leaking too much to faviconkit.com

### ISSUE THREAD

**Issue by LegitLlama** [CanisLupus/swift-selection-search#190]
GREETINGS&THANKS:

Hi,

Thanks for this great add-on that resurrects a functionality that died somewhere between Firefox 20 and 50, and improves on it while remaining lightweight, fast and fully configurable. I really have no idea why no variant of such an empowering feature is not included in vanilla browsers, so thanks for this really smooth implementation!

&nbsp;

ISSUE:

As described in the title, the URL for the search engine icons is retrieved through ```faviconkit.com``` by default, which means this website can get up to the full list of search engines a person uses, especially if they load them through ```search.json.mozlz4```. I understand the purpose of this site, but IMO it would be nice to be able to change the default.

In particular, an empty icon URL field should probably translate to SSS using the sphere icon Firefox displays when it doesn't have a proper icon. This icon can be seen with URLs such as ```about:networking```.  (Additionally, this issue's suggested default URL field being left empty should probably translate to the sphere icon being default)

Thanks for your time

&nbsp;

SIDE QUESTIONS:

1. Can you confirm that the network requests for icons occur only once, and icons are then stored permanently on the user's computer as long as the extension's permanent storage isn't deleted ? (I assume SSS uses the kind of extension storage that doesn't get wiped with the CTRL+SHIFT+DEL data clearing UI)

2. Which API are you using to create the small panel on text selected ? Does it involve injection into the page, or something on the browser level merely covering the page, like the right click menu ?

**Comment by CanisLupus** [comment]
Hi! Thank you for the kind words, I appreciate them and I'm glad that you like it. :)

So, onto the issue:

This is an interesting request. Despite the fact that you can change the icon URL while adding a new engine (by writing anything in the icon URL that is not an empty string), you cannot do that for the `search.json.mozlz4` import, so this is an extra-valid concern. For cases with an unknown URL the best would probably be to generate an icon with a letter, though.

For the side questions:

1. Yes, one request. SSS always uses its own icon cache when displaying the popup or the context menu. It also comes with pre-created caches for the icons enabled by default. When it downloads an image for the first time in the options menu, it compresses it to a max of 48x48 pixels and then stores it in the settings for constant reuse.

2. I'm injecting the popup into the pages as a page script, though I've recently thought it would be better if it was a browser panel to avoid compatibility issues with some websites and eventual privacy problems. Not sure if such a panel can be created with WebExtensions or not, though. It's something I'd have to research. :)

Cheers!
Daniel

**Comment by LegitLlama** [comment]
> Despite the fact that you can change the icon URL while adding a new engine (by writing anything in the icon URL that is not an empty string), you cannot do that for the search.json.mozlz4 import, so this is an extra-valid concern.

The last three words make me think I don't need to say the following, but just in case: When I add 10 engines through ```search.json.mozlz4```, I'm leaking all of them. But when I add 10 engines manually, there are good chances that I will also be leaking all of them. The request to ```faviconkit.com``` happens as soon as a new engine is created. If I then change the engine URL, another request will be sent as soon as focus leaves the engine URL field. SSS is very reactive in loading the favicon, which is good, but as long as it is this reactive and the default icon URL involves ```faviconkit.com```, there will be network requests to it. (Though fortunately, they only happen once per engine as you confirmed)

> For cases with an unknown URL the best would probably be to generate an icon with a letter, though.

Certainly more distinctive to construct a relevant icon locally than to use the wireframe sphere icon, indeed.

&nbsp;

Thanks for all the replies! :)

> Not sure if such a panel can be created with WebExtensions or not, though. It's something I'd have to research. :)

Sadly, it seems that it might not be possible, otherwise Gorhill could have thought about it [here](https://github.com/uBlockOrigin/uAssets/issues/7129#issuecomment-602225191) when he recommended [browser.tab.injectCSS()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/insertCSS). Oh well, I set the pop-up to only appear on middle-click now, and to compensate I moved SSS's item at the very top of Firefox's right click menu using ```userChrome.css```:

    #jid1-kdtticj6wxvafa_jetpack-menuitem-_sss  {
        -moz-box-ordinal-group: 0 !important;
    }

**Comment by CanisLupus** [comment]
> But when I add 10 engines manually, there are good chances that I will also be leaking all of them. The request to `faviconkit.com` happens as soon as a new engine is created. If I then change the engine URL, another request will be sent as soon as focus leaves the engine URL field.

While this is true, I meant something a bit different (and weird):

1. If you add a new engine it will be google.com for starters, and that will indeed leak to faviconkit.com, but no leak actually happens if you already have an engine that uses the icon `https://api.faviconkit.com/www.google.com/64` (such as the default one that comes with SSS) because SSS reuses it from the cache since the link is the same. But probably no one but me would know this!
2. If you now replace the icon URL on the new engine with something else, like another link or just a letter, or something else, it will stay like that, so even if you change the search URL now, nothing will be requested from faviconkit. However, not touching the faviconkit link or clearing it indeed will cause the URL link to update after you write the search URL.

So, there is a way to not leak anything, but I'll be the first to say that it is cumbersome and no one would magically know they can do this. ;)

> Sadly, it seems that it might not be possible, otherwise Gorhill could have thought about it here when he recommended browser.tab.injectCSS()

I see you are very thorough in your search through these issues! That may be true, although Gorhill may have assumed that I NEEDED to have a page popup. But yeah, WebExtensions are more limited than the old add-ons so it may also turn out to not be possible.

I'll research this a bit when I can!

**Comment by LegitLlama** [comment]
Thanks again for your time and your thoroughness! This add-on is in good hands.

**Comment by CanisLupus** [comment]
Hi @LegitLlama! SSS version 3.44.0 adds a new option:

![image](https://user-images.githubusercontent.com/532708/89123451-5e116480-d4c7-11ea-99da-ddc01da2ce30.png)

When it passes the Mozilla review everyone should be able to set it to None to avoid sending information to faviconkit.

Two things to note:
1. "None" is really "none", so it doesn't try to create any default icon with a letter or anything. Unfortunately that would be quite a lot of work at this point, so I figured I would allow people to fix the privacy issue for now, if they wish, and set the icons themselves.
2. Some of the default icons (the ones that come with SSS) still use favicon kit and some requests will be triggered when first entering the options page. I intend to change those as well later.

**Comment by LegitLlama** [comment]
Neat, thanks ! No more using the workaround then :)

I noticed the update before your comment here, so it sounds like Mozilla can be super fast in reviewing updates even to recommanded add-ons. (They're reviewed manually before being made live right, like old times add-ons ? Glad to see a hint that they've got a properly staffed team.)

**Comment by CanisLupus** [comment]
Great! :)

Interesting, I only got their email saying it was pending review about 3 hours after my post here. And only 11h ago did they send me the email saying it was live. I don't usually check before that, so I'm not sure when exactly it happened.

And yes, they do review recommended addons manually and are usually pretty fast. :) If I remember correctly, when I submitted this update the review queue had 24 reviews in wait (not sure what addons are included there, probably not only recommended ones. 24 is pretty high, actually.)

I believe they have it automated enough where weird API usage or permissions are concerned, though. It's also unlikely that they test much more than the very basic in terms of usage, especially if they just diff the code with the previous version. But I have no clue about the review process, honestly. :)

**Comment by CanisLupus** [comment]
Took a while, but in SSS 3.47.0 I changed the default engines so that none of them rely on faviconkit. So, even for those, no requests should now be made to that site (applicable to new SSS users and users who reset their engines at some point). :)

I think that finally closes this issue.

Cheers!
