### ISSUE TITLE
Allow context menu search to differentiate between middle-click and left-click

### ISSUE THREAD

**Issue by LegitLlama** [CanisLupus/swift-selection-search#191]
Hi,

The pop-up UI allows different search behaviour depending on whether you left-click or middle-click on the search engine icon. This behaviour is handled in SSS's options. For example, left-clicking could be set to search in the current tab, and middle-clicking in a new tab.

It would be nice that the context menu allows the same thing. Currently, only one behaviour is allowed for both types of clicks.

Thanks for your time!

**Comment by CanisLupus** [comment]
Thanks for the suggestion!

This has some similarities in implementation to issue #160, so I'm leaving a reference here (definitely not a duplicate, though).

**Comment by CanisLupus** [comment]
Also done! In version 3.43.0 you can now choose the left, right, and middle click behaviour for popup icons AND context menu icons (previously only left/middle click was available for popup and only left click for the context menu).

Cheers!

**Comment by LegitLlama** [comment]
Great, thanks. Works fine and all. Not sure which settings I'll end up keeping long term yet, we'll see!
