### ISSUE TITLE
Note on settings lost on version 3.43.0 (I reverted that version and submitted a fix)

### ISSUE THREAD

**Issue by CanisLupus** [CanisLupus/swift-selection-search#195]
UPDATE: Version 3.43.2 already available with the fix.

---------------------------------

I'm creating this issue temporarily in case anyone comes here looking for help.

In the last update (3.43.0) I completely forgot that I had some code for testing that cleared the settings on start... :( That code was added weeks ago, commited, and I never thought about it again. And it was BAD.

I am SO SORRY about this!

I'm not sure how many people were affected, but I reverted to the old stable version (3.42.1) and submitted a fix (Mozilla will still have to review the submission). The version was up for about 2 hours until a user thankfully contacted me. I will also take actions to make sure that this particular problem doesn't happen again, even if I forget.

Version 3.43.2 will fix this when available. For now the addon will remain at version 3.42.1, since I disabled the problematic version.

If your Firefox updated the addon automatically to the problematic version, please let me know if you need help recreating engines or something else! Again, I'm very very sorry.

Daniel

**Comment by in4u** [comment]
Damn, it's a big oops moment man! Fortunately, I had a backup of exported settings but it was still a mess since they were being reset on every launch. Thought it may have been issue with one computer. Updated on other too and things were botched up there too!

Came here to post an issue and saw your post. Have now updated again to your fixed version and imported settings. Looks like everything is normal again. But I wonder what happened to those who didn't have a settings backup and got hit by the auto reset!

**Comment by CanisLupus** [comment]
Yeah, this is easily the biggest mistake I made with SSS. I'm very very sorry! :(

I hope you didn't lose too many engines, but that is wishful thinking; some people may have lost everything. I also wonder how many people were affected. 2 hours is a lot of time when updates are automatic...

I'm already changing my build script to warn me if code similar to "storage.something.clear()" is present in the code, so it will avoid future mistakes like this. If only I had noticed it in the commit 3 weeks ago... Sigh.

Please tell me if I can help in any way. I've disabled the version but I'm not sure if Firefox reverts the version for people who had it already. Did you have to update manually to the specific version 3.42.1?

**Comment by in4u** [comment]
Don't know about others but in my case, all customized settings and engines were lost, like a complete reset. I was so bummed out by it that I didn't wait for Firefox's auto update and just updated manually after seeing your post.

I don't know how FF handles the update frequency or reversions. The only thing I can suggest is that you may consider pinning this issue for a day or two for people coming here to check and/or report. And maybe also put up a notice on the AMO page or link to this post for the benefit of others affected by that short-lived update.

**Comment by ZIEXED** [comment]
I was going to open an issue about this but seems like someone contacted you first,
I lost all my engines and settings but thank God I do a backup every time I add an engine; so my last backup was just a week ago, many of my engines icons are customized I edited or made for myself and I deleted the originals after putting it as a DataURI in my SSS settings, so if I lost my engines (+70 engine)... just thinking about it is terrifying.

Regarding how the updates are handled, AFAIK those who have v43 won't be reversed back to 42 even if you disabled it; until a new version is approved.

**Comment by LegitLlama** [comment]
Heh, I got it twice.

Manual update --> Lost settings --> Restore them manually --> Close browser --> Reopen --> Lost settings --> Learn that AMO rolled back --> Uninstall --> Reinstall working version from AMO --> Restore settings manually and export them.

I lost 15 minutes of my life, I think I'll survive :)

**Comment by CanisLupus** [comment]
Damn... sorry everyone. I know that you 3 are all familiar with this repository and it affected all of you, so I can only imagine how many people were affected in this 2 hour period...

Well, since I can't fix the past I'm making sure this won't happen again. I have made mistakes or introduced bugs before, but deleting settings (and mainly engines) is a WHOLE new level of mistake.

I've pinned the issue (thanks for the suggestion, @in4u) and updated the addon page with a warning. I'll also be watching for reviews and emails. I wish I could accelerate the review process for the new version as well, but that's not up to me, unfortunately.

**Comment by LegitLlama** [comment]
> so I can only imagine how many people were affected in this 2 hour period...

I'd venture a guess that most users don't touch the default settings, or barely. I would say that people like us and the person who contacted you are probably more like canaries in a coal mine than representative of the larger user base :)

Either way we'll find out in some days, by looking for negative comments on AMO and how the amount of users is affected!

Thanks for the quick reaction.

**Comment by ZIEXED** [comment]
Firefox auto update extensions only once every 24h "the chance for the auto update to trigger during those two hours" so I think the number of affected users are low.
extensions auto updating is disabled on my end so I do check manually for updates.
however this reminds me again the importance of SSS to me,
it makes me overwhelmed by feeling of the need to express my thanks and appreciation once more <3

**Comment by in4u** [comment]
I also keep auto updates disabled. Unfortunately, manually checked for updates at the wrong time.

Anyways, no need to be too hard on yourself @CanisLupus. Well, shit happens but we live and learn. Glad that you fixed it quickly. Cheers!

**Comment by CanisLupus** [comment]
Thank you all so much for understanding. :)

I hope you're right and not too many people (especially those that have many custom engines) were affected. The statistics page only updates daily, maybe I can check later tomorrow.

>  The remaining problem is that AMO doesn't seem to want to downgrade people to the last enabled version. Mozilla should probably improve that.

Yeah, this feels like it could be improved. An option when the author disables a version, for example, which would cause Firefox to downgrade the addon to the previous version.

> so I think the number of affected users are low.

I sure hope so...

> Firefox auto update extensions only once every 24h

That is good to know!

> it makes me overwhelmed by feeling of the need to express my thanks and appreciation once more <3

Aww thank you! ❤ :) You are welcome!

> Well, shit happens but we live and learn. Glad that you fixed it quickly. Cheers!

Thanks! I'm glad it was quick enough too. In the meantime I've tried contacting someone from Mozilla for the addon review but they have no obligations whatsoever and may not even see the request soon, so the update will probably be up in "normal" time.

Cheers!
Daniel

**Comment by in4u** [comment]
I just updated to 3.43.2 now and it's working fine. Must confess that the reason I was eager to update (to the previous buggy 3.43.0 version) yesterday was reading the release notes mentioning the new feature of popup icons' right click options availability. More specifically, I was hoping for an option `Open in new private window` (like [Glitter Drag](https://github.com/harytfw/GlitterDrag)). I think you're already aware of such a feature request @CanisLupus, just hoping to see it implemented soon!

**Comment by CanisLupus** [comment]
Good to hear that it's finally working. Yeah, this version only adds the possibility of using the right click for the already existing ways to open the search, and private window is not one of them yet, unfortunately. Issue #160 suggested this but in a different way, and I never got around to it. Adding it as an extra "open behaviour" would probably be easier. Can't promise when, but it's noted down. ;)

**Comment by in4u** [comment]
Yeah, I saw that issue but am personally not too keen on using complex modifiers or combinations for such basic tasks. Simply adding private window option in the "open behaviour" list which can be used across left, right, middle clicks and even context menu allows enough flexibility, at least for me.

**Comment by CanisLupus** [comment]
I think it has been enough time, so I'll close this issue. Thanks to everyone for their support on the aftermath of this mistake. ❤
