### ISSUE TITLE
add search for text on "google" new tab

### ISSUE THREAD

**Issue by travisim** [CanisLupus/swift-selection-search#199]

**Comment by ZIEXED** [comment]
I don't know if this is what you meant, but I really wish if I can set my popup menu as my newtab centered with just the same settings and size.

**Comment by CanisLupus** [comment]
Hi @travisim, I'm also not sure what you mean by this! Please provide some more info in the description. If you mean to open searches in a new tab please look at these:
![image](https://user-images.githubusercontent.com/532708/83947702-94f13400-a810-11ea-8050-94e5619321e8.png)

@ZIEXED If you'd like please add a new issue with a suggestion. ;)

**Comment by CanisLupus** [comment]
Closing for lack of new info!
