### ISSUE TITLE
Congrats on 1000 users!!!

### ISSUE THREAD

**Issue by Gitoffthelawn** [CanisLupus/swift-selection-search#20]
Woohoo!!!  Way to go!

**Comment by CanisLupus** [comment]
Hehehe thank you very much! ;)

The statistics are interesting too. 40% of SSS users use Russian as their language. SSS seems strong there! Only about 33% use English.

**Comment by Gitoffthelawn** [comment]
Love the new tag! :)

I wonder if it was highlighted in a blog that caters to Russian speakers.

Around the world, people love Swift Selection Search! :)

**Comment by CanisLupus** [comment]
The usage seems mostly stable, though, with no standout peaks. I'll probably never know why. :)

**Comment by CanisLupus** [comment]
Closing this! ;) hehe
