### ISSUE TITLE
Use keyboard shortcut to choose search engine after pop up

### ISSUE THREAD

**Issue by Jinkiesz** [CanisLupus/swift-selection-search#203]
It would be nice if you could open your preferred action/search engine after the pop up opens using a keyboard. For example if I click 1 on the keyboard after the pop up opens, it would copy the text. If its 2, it would open as a link, 3 it would search on duckduckgo etc

**Comment by CanisLupus** [comment]
Hi @Jinkiesz, thanks for the suggestion. This was actually already requested (in a similar way) in issue #149, so I'll be using that thread to keep track of this. I hope you don't mind me closing this issue, You can subscribe to the other one if you want to be notified of changes. :)

Cheers!
Daniel
