### ISSUE TITLE
on dragging link, duplicate new tabs opened for same link 

### ISSUE THREAD

**Issue by CondomsPreventCoinkydinks** [CanisLupus/swift-selection-search#207]
set option for dragged links to open in background tab. currently, dragging link causes two tabs to be opened for the same link and one of them is given focus instead of staying in the background? any advice? thanks.

**System info:**
- Browser: Firefox, 
- Browser version: latest, 78
- System: Windows 10

**Comment by CanisLupus** [comment]
Hey! I'm confused. What do you mean by "dragging link"? I must ask because in SSS there are no options related to dragging links. :)

You just select some text, click the search engine you want and then it opens according to the opening behaviours you set in the options menu (for left, right and middle mouse button clicks).

Cheers!
Daniel

**Comment by CondomsPreventCoinkydinks** [comment]
ok, this is embarrassing. first, thanks for the quick response, and thanks again because you made me realise what the problem was: 

1. i'm a moron. long standing genetic issue, you can't help with. 
2. i've got my addons confused. for a moment i thought swift selection was doing the job of firedrag! obviously that is not the case. then you made me realise firefox sync has readded firedrag and quickdrag addons both to my refreshed FF, which is why i was getting duplicate tabs. all resolved now.

going to change my review from 4 to 5 stars. thanks again and apologies for the confusion and wasting your time. your addon is excellent.

**Comment by CanisLupus** [comment]
You reply made me laugh. :D

It actually occurred to me from the text that you might have some addons mixup, but you might also have meant something different so I went with that.

It's no problem at all. ;) Judging from what caused it (Firefox Sync re-adding addons) it could easily happen to anyone. By the way, I really appreciate the review. Thanks! :)
