### ISSUE TITLE
Load browser search engines silently does nothing 

### ISSUE THREAD

**Issue by whxvd** [CanisLupus/swift-selection-search#209]
1. Go to 'SSS Options'
2. Click on 'Select search.json.mozlz4'
3. Select the correct file (checked with mozlz4-edit add-on: the selected file does contain my list of search engines)

Then nothing happens. Expected: Current list of (just active, maybe) Firefox search engines gets appended to list of SSS search engines. (Not) happens in both, vanilla SSS, and after deleting all default SSS search engines.

Arch Linux (x86_64)
Arch Linux package firefox 79.0-1

I am illiterate in Web- and Firefox-Add-on-programming, but literate in programming in general. I may help to debug if advice is given.

**Comment by CanisLupus** [comment]
Hi and thanks for the report. I received an email yesterday with the same issue, and I just confirmed that this is happening.

My theory right now is that Firefox changed the internal structure of the search.json.mozlz4 in a recent version, so what SSS looks for to find the engines is not there anymore or has changed name. I'll take a look ASAP.

**Comment by CanisLupus** [comment]
So, I looked into this and I have bad news. The search.json.mozlz4 file doesn't contain enough information for SSS anymore. Previously most engines contained within had at least one URL definition with parameters, but now, from what I understand very superficially, they are controlled via small "plugins" for each search engine in Firefox, and so in search.json.mozlz4 they only say "_isAppProvided": true, and there's no additional info.

It remains to be seen if I can get the missing info from somewhere else easily or not.

SSS could simply implement code to import the existing engines via the WebExtensions API, as seen in #106. However, I never did that because of the reasons contained in that thread. In summary, they don't give access to the engine URL at all, so you are just supposed to call the API to search using that engine, causing search costumizations in SSS like replacements and opening behavious to be unusable for those engines.

**Comment by CanisLupus** [comment]
I'll be trying to "fix" this by using the search API, which will also complete #106, despite the limitations this has.

Likely there are other, more convoluted, ways to get the search URLs, but this will be enough for most users that don't want to customize their engines and it will also get rid of all the code that reads and decodes the mozlz4 file, so it may be for the best.

**Comment by whxvd** [comment]
Cool. Thank you!

**Comment by CanisLupus** [comment]
You're welcome! Thanks again for reporting this. Bugs have priority. :)

I implemented this and submitted a new version to Mozilla, which will be awaiting review. It's version 3.45.0.

Please let me know when you are able to try it. The imported engines are more limited, but it's probably the best solution right now.

**Comment by whxvd** [comment]
I temporarily installed `3.45.1` via "Load Temporary Add-on" on `about:debugging#addons` and tested a bit. Worked flawlessly in all cases.

Really nice add-on.

**Comment by CanisLupus** [comment]
Thank you for confirming! :)

Just out of curiosity, did you get 3.45.1 by building this repository? Or is there some way I don't know of getting it from Mozilla Addons before the review?

Cheers!

**Comment by whxvd** [comment]
I went through the steps for building mentioned in `README.md`, using the `about:debugging#addons` and "Load Temporary Add-on" method.

In order to be (somewhat) sure that afterwards the `3.44.0` SSS does not get confused by `3.45.1` configuration, I then removed the plugin, reinstalled it from `addons.mozilla.org`, and quickly configured it for one search engine (english german dictionary).

How long does it usually take for Mozilla to review a new version?

**Comment by CanisLupus** [comment]
> I went through the steps for building mentioned in `README.md`, using the `about:debugging#addons` and "Load Temporary Add-on" method.

Ah I see, that's what I expected but I was not sure. :)

> In order to be (somewhat) sure that afterwards the `3.44.0` SSS does not get confused by `3.45.1` configuration, I then removed the plugin, reinstalled it from `addons.mozilla.org`, and quickly configured it for one search engine (english german dictionary).

That was smart thinking, it's definitely safer to do that when downgrading. In such a situation you can also export your settings/engines in the options menu before upgrading, and restore them later after re-installing the old version again.

> How long does it usually take for Mozilla to review a new version?

It varies, but usually it's somewhere between a handful of hours to about 2 days. Not sure how the holidays affect this, however.
