### ISSUE TITLE
How to make pop up keep staying when click one website.

### ISSUE THREAD

**Issue by kktt007** [CanisLupus/swift-selection-search#210]
**Describe your suggestion**
I want to click more website, but once i click on one icon, the pop up disappers. 

I used selection search on chrome, i could click icons one by one. 

Maybe i didn't find how to configure it. Many thanks.

**Comment by igorofc** [comment]
Hi @kktt007. 

Follow these steps:

1. Go to the extension's preferences page.
2. Under the 'Popups/icons behaviour' section, uncheck the option 'Hide popup on search engine click'.

**Comment by kktt007** [comment]
> 
> 
> Hi @kktt007.
> 
> Follow these steps:
> 
>     1. Go to the extension's preferences page.
> 
>     2. Under the 'Popups/icons behaviour' section, uncheck the option 'Hide popup on search engine click'.

Many many thanks. @igorofc .
You solved my issue. This is the answer.
