### ISSUE TITLE
Search for a phrase ("Problem report") instead of all results that include the words (Problem+report)

### ISSUE THREAD

**Issue by gitupdown** [CanisLupus/swift-selection-search#211]
I want to set certain search engines to search for phrases and not simply word combinations.
For instance, 
1. On a Github [problem report page, ](https://github.com/CanisLupus/swift-selection-search/issues/new?assignees=&labels=&template=problem-report.md&title=) you see the phrase, "Issue: Problem report" and want to Google it.

2. You use your mouse to select the phrase, "Issue: Problem report".  If you go to Google.com and use quotation marks around the phrase at issue, you'll get fewer than 40,000 results. 
_(On my browser address bar, the url for this results page reads google.com/search?q="Issue%3A+Problem+report”  ; when I copy the address and paste it here, it comes out as google.com/search?q=%22Issue%3A+Problem+report%22 )_

3.  But just using ={searchTerms},  you get more than **2 million** results containing any approximate combination of the three words _issue_, _problem_, and _report_ (i.e, the url google.com/search?q=Issue%3A+Problem+report)

I see that you can use slashes to replace, perhaps, a space (" ") with a plus sign ("+"). But I can't figure out how set the search url to put quotation marks around a string of words in order to search for a phrase. 

**System info:**
- Browser: Firefox
- Browser version: 79.0
- System: Windows 10

Any advice or enhancements would be greatly appreciated. Anyway, thanks so much for your work on this. 

EX.1: Search as phrase = under 40,000 results
![SSS Search phrase 39k results - Copy](https://user-images.githubusercontent.com/70115153/90991415-f22a9500-e576-11ea-974c-07ce0c94b08e.png)

EX.2: Current Default-Find all 2 million+ pages that include words contained in the phrase
![SSS Search no phrase 2m results chrome - Copy](https://user-images.githubusercontent.com/70115153/90991414-f191fe80-e576-11ea-89ca-2dd31e72d16d.png)

**Comment by ZIEXED** [comment]
If you want to search for `"Issue: Problem report"` instead of `Issue: Problem report` just put `"{searchTerms}"` instead of `{searchTerms}`
if you want to replace space with `+`  then use `{searchTerms{ |+}}` _(put it between quotation marks if you want both) `"{searchTerms{ |+}}"`_

**Comment by CanisLupus** [comment]
Hey @gitupdown, could you tell us if what ZIEXED said solves the problem for you?

An additional possibility is using quotes ONLY if the selected text contains a space between some characters. You could do this with a regex like `{searchTerms{re/(.+ .+)/g|"$1"}}`.

**Comment by gitupdown** [comment]
@ZIEXED Thanks so much. Works perfectly. @CanisLupus sorry for the delay, and thanks for advising me to report back. It didn't occur to me that I should do so.

**Comment by CanisLupus** [comment]
No problem, thanks for reporting back! ;) I'll close this issue now.
