### ISSUE TITLE
Could you pls make a chrome version?

### ISSUE THREAD

**Issue by minshifu** [CanisLupus/swift-selection-search#234]
This is a super great addon. It is a pity that chrome browser does not have a comparable extension. Could you pls make a chrome extension? Thank you and best regards!

**Comment by jdreesen** [comment]
Please have a look at the readme ;)

Also, this is a duplicate of #184, #148 and #132.

**Comment by CanisLupus** [comment]
Thank you so much for the help @jdreesen 😃

Hi @minshifu! Indeed, the links posted above by Jacob should explain why there's no Chrome version. Also, right now SSS is not actively being developed (see #230).

I'll close the issue now, I hope you understand!
