### ISSUE TITLE
SSS must be changed from Add-on SDK to WebExtensions before the end of 2017

### ISSUE THREAD

**Issue by CanisLupus** [CanisLupus/swift-selection-search#24]
In [this blog post](https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/) from November, which I have only now read, Mozilla mentions that from the end of 2017 onward, they will only support add-ons created with WebExtensions. Quoting:

> By the end of 2017, and with the release of Firefox 57, we’ll move to WebExtensions exclusively, and will stop loading any other extension types on desktop.

I'm writing this to let you know the current state of things, even knowing that few people will read it here.

SSS was created with the Add-on SDK. I've tried to keep up with the changes, adding multiprocess support despite the fact that I've had to replace a great deal of code to get that working. Unfortunately, I don't know if I will be able to meet the WebExtensions standard.

I haven't been able to work on SSS in recent weeks. Moving to WebExtensions would require a complete reworking of code, and therefore a lot of time. It's not that SSS is large by any means, but I can only work on it in my spare time, and only if there is motivation and there aren't more things to work on or more pressing matters. Besides, web things are not my area of expertise and, as you can see in Firefox, it's an ever-changing environment.

I'm myself a daily user of SSS and I like that it exists because it's useful, but I've taken down the option to contribute from its page on AMO because I don't feel I would be able to correspond to expectations created from that contribution.

I _have_ looked into moving to WebExtensions before, a few months ago. Some features REQUIRED by SSS aren't, to my knowledge, even present in WebExtensions - at least currently, if ever - such as the ability to read the list of search engines from the browser. Some users would be happy with being able to define their own engines in SSS, but if that is the only option, most people won't (me included). If everything required to get SSS on WebExtensions is available, I will at the very least try to port it, sooner or later.

Daniel

**Comment by CanisLupus** [comment]
Here's a statement from another add-on developer (I got the message from using one of his addons, but it can also be seen in this link):

https://framasphere.org/p/2778305

After a year and a half of work on his add-ons (spare time, of course) to make them compatible with multiprocess Firefox, Mozilla announces that all add-ons will soon HAVE to be made with WebExtensions. Great. :|

**Comment by Gitoffthelawn** [comment]
Hi Daniel,

I'm saddened by your message.  At the same time, I totally understand.

I read [Luis Miguel's message](http://fasezero.com/lastnotice.html) soon after he wrote it.  I felt his pain.   It was palpable.

I think Mozilla has done a poor job supporting and rewarding their extension developers.  They have alienated so many talented developers, which is a loss to the entire community.

I personally think Mozilla is making a tremendous mistake.  Unfortunately, even with this massive blunder, there are no better alternatives than Firefox.

I think Firefox still continues to be so popular largely because the alternatives are so undesirable.

Being able to configure and customize every aspect of the browser's UI is Firefox's claim to fame.  And now they want to destroy that.

*Regarding Swift Selection Search,* I feel that it will only be a small detraction to have to manually enter search engines.  Once you've done it, you'll be all set.  We will all have to waste an hour or two of our lives doing it, but SSS is so valuable, it will be worth it.  It will also have the benefit of being able to quickly add new search engines with precise parameters, which is cumbersome within Firefox itself.

I estimate that over 98% of my search engine use is through SSS or bookmark keywords, so I probably would just run Firefox without any search engines installed and simply enter existing engines into SSS.

I'm curious... strictly curious... how much money you've raised through the contributions system.  Please feel free to decline to state... I won't be offended in the least!  I'm just curious... nothing more.   I'm not implying that you have any obligations... all contributions you've received are just small tokens of appreciation. :-)

In pure unadulterated selfishness, I want you to continue to make SSS compatible with Firefox in the future.  But since this is a hobby in your spare time, and not a job, I completely understand whatever decision you decide to make.

Filing bug reports on bugzilla with features you need is one way to encourage Mozilla to make Web Extensions more versatile.  I still have hope that Mozilla will abort their self-destructive path, but given Mr. Miguel's experiences, my optimism may be misplaced.

Based on past experiences, I'm guessing Mozilla will delay any version of Firefox limited to only Web Extensions.  At the same time, slowly making the transition to a Web Extension version makes sense.

Mozilla seems dead set on crippling Firefox.  It's a real shame and a loss for us all.

I want to take a moment to personally thank you for all your kindness, your friendliness, your generosity, and your hard work.  I hold you in the highest regard as a developer, but more importantly, as a person.

**Comment by CanisLupus** [comment]
Hi,

First of all I want to say that I deeply appreciate your message and very kind words. :) Thank you. You have always been very active and interested in SSS's development, and you make me feel like I'm doing something really important for other people, instead of just for me. ;)

Regarding SSS, I understand that some users wouldn't mind (or would even prefer) to be able to define their own search engines, though I imagine they would be power users, mainly. I don't find this ideal but will have to think about it. :)

I still use Firefox and intend to keep using it, at least in the near future. Like you, I don't find the alternatives great. I even understand the forced move to WebExtensions for new add-ons. What I don't understand is why the move is also for existing add-ons while there are still so many things that can't (or won't ever) be achieved with the WebExtensions API. Why do we _have_ to port our add-ons, even if it's impossible? Some add-ons will simply cease to exist because their developers won't be able to update, or won't even feel like they should. *sigh*

As for the contributions, it's no problem to reveal it, particularly because the answer is quite simple: I received nothing. :p I only had the contributions up for about two months (maybe a few more weeks), though I may be mistaken. I have a mostly clear to-do list and also user suggestions for SSS, so I figured that I could let people see them and contribute if they wanted, raising SSS's development in my list of priorities.

I'm not even surprised by the fact that it did not raise any money. Nevertheless, as I figure out what I want to do with SSS in the WebExtensions world, I've taken contributions down to avoid any possible disappointment or frustration from SSS users (in having contributed only for development to halt).

NOTE: Truth be told, I can't be sure that I never got a contribution, because I don't see a place in my account that shows me the state of contributions (maybe I just didn't see it), but I didn't receive any sum from Mozilla anyway.

I have checked a few bugzilla pages that mention access to search engines and closely-related APIs, but nothing that seemed like it was going anywhere. Maybe I have to insist.

Last time I wrote something in bugzilla it was for a already-then-longstanding bug that made it impossible to port SSS to multiprocess Firefox even when using the so called "compatibility shims". I never got a response and it never got fixed, so I had to circumvent the problem and re-implement things to avoid using the text selection API in the SDK. At least I didn't need the shims after that.

Things look a bit... weird, for some parts of Firefox's development. Luís's message was a bit painful to read, even not knowing him. It's quite sad... We'll see how this goes.

Again, thank you for taking the time to write. :) You're awesome!

Daniel

**Comment by CanisLupus** [comment]
OK, after a long period of denial, I finally decided to actually try to port SSS to WebExtensions, instead of just looking at what I CAN'T do. ;) I've ported a good portion of SSS (some parts require many changes; others very little, so it's a mix). For large extensions it would not be pretty!

As expected, WebExtensions have some current limitations that affect SSS in some way:

1. No way to read the search engines from Firefox.
2. No way to have user-defined hotkeys (must be defined statically and can never change).
3. No icons for engines in context menu.

1 is critical and I know of no alternatives that don't change the original SSS idea.
2 is probably solvable by using an external JS library for key inputs (I wouldn't want to reinvent the wheel and implement one that works for both Windows/Linux and Mac), though I'd very much like to avoid bloating every webpage with code just because SSS needs it.
3 is hardly a big problem, I think. The API has nothing for icons in the context menu (that I know of). Worst case scenario: search engines in the context menu will only have names.

Furthermore, user settings will very likely be lost on an upgrade to WebExtensions. In some way this is good because I wanted to clean some things up. It is inconvenient for the users, though.

The rest currently is working and seems doable, including the much needed handmade settings page.

Cheers!
Daniel

**Comment by Gitoffthelawn** [comment]
Hi Daniel,

I'm enthusiastic that you had a chance to look at it!

WebExtensions still have a little ways to go before their sole use is enforced, so it's possible they will improve before then.  I know some devs are posting bugs on bugzilla to let Mozilla know about their specific needs/wants.  You may consider the same.

In regards to your list above:
  1. IIRC, we had different opinions on this previously... regardless, we still do! :-)  I think manually entering search engines one time in exchange for unlimited (and potentially indefinite) use of SSS is a small price to pay.  Perhaps you can even simplify it by having SSS read a text file that just happens to be in the identical XML format as the current search engines. :)
 2. At least for me, not a big deal.  I don't use any of the hotkeys for it... actually I forgot that there were any.  Keyboard fanatics might feel differently, but we can always start a GoFundMe and buy them all pointing devices...  ;)
 3. That's a little bummer, but as you say, it's hardly a big problem.  If nothing is going to have icons, then nothing will have icons.  Personally, I rarely use the context menu for SSS functionality.
 4. Okay, you didn't number this one, but I won't hold it against you. ;)  User settings being lost in the upgrade isn't great, but I figure if I have to spend an hour of my time setting it all up again, it will be well worth it.   Plus if it enables you to clean up the settings a little, it might be a good thing in the long haul.  No matter what, I'll know that you spent much more time rewriting for WebExtensions, so whatever time I have to spend (and other users have to spend) setting things up again is something that none of us should complain about.  I'm not saying there won't be complaining (this *is* the internet, after all), but none of it will be *reasonable* complaining!

Overall, it sounds like converting to WebExtensions will be possible, which is exciting news.  I honestly don't think any of those items are deal-breakers.  I know you're really concerned about the first item, but I think it'll be okay.  If there were a million current users, I would have a different opinion (new support address: *dev/null*), but with under 2,000 users, I think many will be more advanced users.  And given the choice between having nothing and having to enter in the search engines one time, the latter is a million times more appealing...  just like cotton candy ice cream is better than no ice cream at all.  Sure, it's not chocolate or vanilla, but it's still ice cream.  Actually, come to think of it, cotton candy ice cream probably would be kinda good...

**Comment by CanisLupus** [comment]
Well, I hope that they improve it in the near future! I have added my experience to bugzilla on two bug reports that made sense for SSS, one of which was about access to the engines. Then I discovered that bugzilla makes your email address public forever, without so much as a warning, when posting. I was a bit baffled by this "spam bot heaven", so deleted my account (that doesn't delete the posts, so it's okay). :)

1. Yes, we have different opinions, but now that I've started the port I'm prepared to surrender to manual engines if the need arises. ;) (or even add that as an option if I can keep SSS as it is)

2. Haha that's true :p My main fear is colliding with other add-ons that define the same shortcuts, but maybe their idea is for the shortcuts to be Firefox-level, maybe meaning that a user can configure shortcuts for Firefox and all its add-ons in the same place...? This would solve it, but it's just wishful thinking on my part.

3. I also very rarely use the context menu, unless I want to search on an engine that's not on the popup panel.

4. Hehe didn't number it because it was not so much a WebExtensions "limitation" as it was a "I didn't research it yet but assume that there's no way to access the old simple-prefs module". ;) I just hope it won't bother too many people. Non-programmers are not likely to know how much time went into an add-on and that's expected. If all goes well they'll barely notice the whole move to WebExtensions except for add-ons that will suddenly cease to exist. They might not understand why they lost their settings, but they should be able to reconfigure SSS quickly (save for the engines part, if SSS can't read them from Firefox).

Indeed, support@dev/null is every programmer responsibilities' dream. XD I guess time will tell what happens. I just wish that this transition was smoother than they made it. Oh, and I've never tasted cotton candy ice cream but it does sound nice... :)

**Comment by jtojnar** [comment]
It should be possible to convert the extension to an [embedded webextension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions), keeping only the search API integration in the Jetpack wrapper and using it through message passing.

**Comment by CanisLupus** [comment]
@jtojnar Thanks for the suggestion, and I wish that was it... but it says right at the top of that page that "Firefox 57 drops support for legacy add-on types, including legacy add-ons that embed WebExtensions. From Firefox 57 onwards, Firefox will not load add-ons of the type described in this document."

Unfortunately, Firefox Nightly is already at version 57 and the beta at 55, so it's fast approaching. I think they still don't support getting the installed search engines in WebExtensions. The best way to track this is probably [this link](https://bugzilla.mozilla.org/show_bug.cgi?id=1352598).

I really wish I wasn't forced to do the "every engine is manually added by the user" way right now. It's more powerful, but many people won't like that.

**Comment by jdreesen** [comment]
Firefox 55 final already got released this tuesday. It's a shame there's no support for reading installed search engines from web extensions yet. But manually adding search engines is still way better than not having this plugin at all!

**Comment by CanisLupus** [comment]
Oh, you are correct, I hadn't noticed 55 was out!

Yes, I think so too. :) I'm just very disappointed with the way they handled the transition. Many add-ons are still simply un-portable and there's nothing devs can do about it.

**Comment by CanisLupus** [comment]
Hey everyone,

To share the current state of SSS regarding search engines, I currently have this:

![custom engines](https://user-images.githubusercontent.com/532708/29710808-e930201a-8989-11e7-837c-cd619238c567.png)

This will be where the user can add or delete custom search engines, reorder them freely and enable/disable them (to toggle their visibility in the popup). I'm also thinking of joining the custom engines list and the SSS-specific icons like "copy selection" and "open selection as link" (also in the picture above) so there would be no more "Show" and "Show at end" options, and users could set their exact order as they wish. Of course, these would have no "delete" button; only the "enabled" checkbox. :)

If and when Mozilla decides to implement access to the browser search engines for WebExtensions, those will likely also appear in this list to be reordered and mixed with the custom ones (also without delete options).

Finally, the looks are still in progress. I would like to remove the "move up" and "move down" buttons and keep only the leftmost ☰ icon to be able to drag (haven't tried it yet), but creating a drag-and-drop interface is harder. I would also prefer if you hadn't to move the mouse after clicking "Add" each time, because the button is pushed by the new entry. However, placing it at the top of the list doesn't feel ideal either because new engines appear at the bottom. (I'll accept suggestions :p)

Cheers!
Daniel

**Comment by Karim-AlHousiny** [comment]
Hi Daniel,

I've an idea about reading the search engines, instead of adding them manually one by one, but I'm not quite sure if you can apply it in WebExtensions.

As I know the problem is there is no way to access the browser search engines file "search.json.mozlz4" which is unreadable.
but anyone can simply "decompress" it and produce a new readable json file using the browser console:

1- about:config
2- set devtools.chrome.enabled=true
3- Dev Tools > Browser Console
4- Copy & Past the following code and execute:
`    function decompress() {
      Task.spawn(function() {
        let cacheFilePath = OS.Path.join(OS.Constants.Path.profileDir, "search.json.mozlz4");
        let bytes = yield OS.File.read(cacheFilePath, {compression: "lz4"});
        let data = new TextDecoder().decode(bytes);
        let jsonFilePath = OS.Path.join(OS.Constants.Path.profileDir, "search.json");
        OS.File.writeAtomic(jsonFilePath, data);
      });
    }
    decompress();
`
Now you have a new readable file for the whole browser search engines, and it would be great if somehow we can import/read the SE from that file.

Hope this helps and thanks Daniel for your time and effort...

**Comment by CanisLupus** [comment]
Hi @Teko101, thank you very much for your suggestion. :)

It indeed works in the browser, but I don't think I'm able to use OS.File in WebExtensions, since there's some understandable sandboxing going on. However, it might be possible to add an HTML "file input" element to the SSS settings page and _let the user select that file (search.json.mozlz4)_. I haven't researched that yet, though. If we're able to do that, then decompressing and reading as JSON should allow importing everything (hopefully decompressing bytes without using OS.File is doable...?), which would definitely be an improvement over _having_ to specify every engine by hand! ;)

I will definitely try it when I can. I haven't had much time lately, but this is the most important issue of all, so it's always what I'm working on when working on SSS. ;)

Cheers!
Daniel

**Comment by CanisLupus** [comment]
By the way, the custom engines view with the "copy" and "open as link" icons currently looks something like this:

![sss-custom-engines](https://user-images.githubusercontent.com/532708/30039323-2966ddb4-91c7-11e7-81c6-60743424cdd3.png)

The drag (☰) icons also work now, so no more "move up" and "move down" buttons. :) In the image I dragged the "copy" and "open as link" icons to the middle of the others so it looks a bit uglier than normal. ;)

**Comment by T-Halen** [comment]
Will the new SSS allow for locally stored icons, instead of remote links for them?  I'm quite happy configuring my own engines in SSS.  Thanks!

**Comment by CanisLupus** [comment]
That would be nice, @T-Halen. I would like to at least be able to download them just to be sure that the link does not become broken at some point. :)

**Comment by CanisLupus** [comment]
[Reading an lz4 compressed text file in WebExtensions (JavaScript, Firefox)](https://stackoverflow.com/questions/46130021/reading-an-lz4-compressed-text-file-in-webextensions-javascript-firefox)

Does anyone know the answer to this question? I've never had any luck with questions about Firefox extensions, and this might be the last thing standing before being able to read the engines from Firefox's files in a WebExtension (as long as the user browses to the correct file).

**Comment by Gitoffthelawn** [comment]
You're officially my last legacy extension.  You know what they say: "Save the best for last".

Any guestimate of an ETA?  No pressure... just curious.

Thanks again for all your hard work... it's truly appreciated! :)

**Comment by CanisLupus** [comment]
Woohoo! Wait... that's not good... :p I have 7 extensions other than SSS and 3 are still legacy. But no, that doesn't mean that I'm not late. :p

Right now, my TODO list for completing the WebExtension is this (very detailed version ;)):

- Maybe save SSS preferences in Firefox Sync instead of local storage? Problem is that I store engine icons as their data (resized to 48x48 if larger) and that's relatively large (max Sync storage per extension is 100KB). I don't want icons saved as URLs because:
	1. URLs may become invalid;
	2. Some secure sites deny non-https content, so some icons wouldn't even show on popup because they have http images.
- Some search engines imported from the browser are "resource://" links, and extensions don't seem to have access to those links, failing to load the images. Most browser engines seem to have Base64 icons already, though.
- From Firefox 56 on, dragging things fails on the extension settings page (can't reorder engines anymore). Additionally, an open dropdown becomes offset after scrolling the settings page (you can do this on any addon that has dropdowns and has enough settings to allow you to scroll the page. Maybe zoom in to force scrollbar?). This looks like a bug and it remains on Firefox 57. I didn't report it yet because Bugzilla makes your email public without even warning you, and I really really really disliked that. :(
- Some hotkeys simply don't work (Ctrl+Shift+X and most or all other letters, actually?). What is going on?
- Restarting the extension (and updating too?) causes popups from previous run to remain on page.
- Need to take better screenshots for Add-on page.

I could push the git repository (I'm working locally) and maybe give you a test build, but I prefer to wait a bit to work on some of these points first. I hoped to get it done before the end of this month to catch the first public release of Firefox 57, but we'll see. Not much time to spare on the coming weekends, unfortunately. :( And some of these points are "unsolvable" for now. :) 

Daniel

**Comment by Gitoffthelawn** [comment]
> Maybe save SSS preferences in Firefox Sync...

Will this still work if users don't have Sync enabled?

> From Firefox 56 on, dragging things fails on the extension settings page...

I noticed this as an issue for the Drag and DropZones WE.  Nothing is draggable for him either.

> I didn't report it yet because...

Try a temp email! ;)

> Some hotkeys simply don't work...

And as you have probably discovered, you can't let users change hotkeys... they need to be static.

> ...maybe give you a test build, but I prefer to wait a bit to work on some of these points first...

No problem... waiting is fine.

It sounds like most of the issues revolve around the configuration UI.  I wondering if it makes sense to release a version that is configured by the user manually editing a json file, and then later release a version that has a proper configuration UI. 

---

BTW, since you are neck-deep in this stuff, I have a question that you might be able to answer: I use userContent.css to modify toolbar button drop-down panels from extensions to customize them to my liking.   Until FF57, this worked fine.  Starting with FF57, this only works on some extensions, but not others.  Any idea why?

**Comment by CanisLupus** [comment]
> Will this still work if users don't have Sync enabled?

Couldn't find info about that, but I suppose it is a normal local storage that has the added feature of being synced from time to time. I could be wrong, though.

> Try a temp email! ;)

I'll probably create an account using another email, yes. :)

> And as you have probably discovered, extensions can no longer let users change hotkeys... they need to be static.

Yup, that was one of the first things I searched for when starting the port (what was possible and what wasn't) and... yeah. :(

I can work around the issues of the preferences UI. Dropdowns being offset I don't think I can fix, but dragging can be replaced with buttons for now (less than ideal, but simple). Apart from that everything works, thankfully.

---

Unfortunately I don't know much about that. I only know what SSS needs me to understand. :) That problem may be due to extensions having custom formatting and overriding your styles, but I never tried using that file.

**Comment by Gitoffthelawn** [comment]
Sounds good! :)

**Comment by CanisLupus** [comment]
The master branch of this repository is now the WebExtension version of SSS. :) I'll have to look into one or two points and I'll be testing it in day to day use to see if it works as expected, but you can try it out if you wish.

It's not as easy to install manually as before (yay WebExtensions...). Before, you could drag a build into Firefox and it would install nicely. Now, the best non-developer way I found is to go to the `about:debugging#addon` page in Firefox, press the "Load Temporary Add-on" button, and select a file in the Swift Selection Search "src" directory (for example manifest.json). This will load the add-on until the browser closes.

It uses the same ID as the current SSS version on the add-on market, so it will replace it, but the old version returns (apparently with settings intact) when the browser closes or you remove it from the same page.

I realize not many will want to go through the trouble of trying it now, so if anyone does and reports any issue you find you'll have my eternal gratitude. ;)

**Comment by CanisLupus** [comment]
Additionally, regarding the previous TO-DO points:

> Maybe save SSS preferences in Firefox Sync instead of local storage?
Not for now. I'd have to find a way to warn people if they were reaching the 100KB limit, which I could do using storage.sync.getBytesInUse() **IF** Mozilla had it implemented (yay WebExtensions). Also, I'm not sure if people DO want it to sync across machines automatically. Maybe a button to sync on demand would be better.

> Some search engines imported from the browser are "resource://" links, and extensions don't seem to have access to those links, failing to load the images.
Couldn't find a way to avoid this, unfortunately.

> From Firefox 56 on, dragging things fails on the extension settings page (can't reorder engines anymore). Additionally, an open dropdown becomes offset after scrolling the settings page.
I reported these bugs, both of which already had duplicates with other info. First one is still going. Second one is fixed in Firefox 58.

> Some hotkeys simply don't work (Ctrl+Shift+X and most or all other letters, actually?). What is going on?
No idea. Reserved by Firefox? Had to change Ctrl+Shift+X to Ctrl+Shift+U, which apparently works. I feel this is prone to break with other add-ons setting their keys, but I don't think I can do anything.

> Restarting the extension (and updating too?) causes popups from previous run to remain on page.
Haven't tried to solve this yet. SSS also doesn't work on already open pages on install.

**Comment by Gitoffthelawn** [comment]
> Maybe a button to sync on demand would be better.

Great idea.

> I reported these bugs...

Yay!

Sounds like you are making great progress!  Thank you.  :)

**Comment by CanisLupus** [comment]
Alright, I'm finally closing this issue! (though you can comment anything related to WebExtensions if you'd like)

I've just submitted the WebExtensions version of SSS to the add-ons page. They accepted it before I could even write the release notes in the page after the upload. ;) (didn't know that could happen). I've also since updated the AMO description with warnings about feature regressions due to WebExtensions.

There will probably be bugs in this version. After all, this was close to a rewrite of SSS. I hope people will understand that the regressions are mostly due to WebExtensions and not be mad about the loss of settings, for example. :( _sigh_

I'll eventually start dealing with the other issues and suggestions. :)

**Comment by Gitoffthelawn** [comment]
Congrats!

Mozilla's new policy is to accept all extensions and review them afterwards... at least that's my understanding of it.

**Comment by CanisLupus** [comment]
I hadn't submitted updates for close to a year, so that's maybe why I'm finding it strange now. There didn't seem to be any mention of a review process, but well, it's live anyway! :)
