### ISSUE TITLE
Multisearch

### ISSUE THREAD

**Issue by harryray33** [CanisLupus/swift-selection-search#240]
Is there a way of searching more than one engine at a time?

Thanks

**Comment by CanisLupus** [comment]
Yes! In the engines list you can use the "Add group" button at the bottom:

![image](https://user-images.githubusercontent.com/532708/148421049-c1c78f4c-9d53-431c-bfcc-702fd19da330.png)

Then select which engines you want to add to that group and write a group name.

Clicking a group will open the search on all engines contained within. :)

**Comment by harryray33** [comment]
Thanks, that useful, but is it limited to the engines that pop up? I would like to include some of the engines that I have added to Firefox

**Comment by CanisLupus** [comment]
You can add the engines from Firefox with the option right below the list :)

![image](https://user-images.githubusercontent.com/532708/148601346-4396aa1e-cf7f-4567-8372-30eb538e7fde.png)

Please also take a look at the "Instructions" section at the top of the options page if you want to make your own search engines, as it can help a lot:

![image](https://user-images.githubusercontent.com/532708/148601432-2cbecf76-fa66-4693-85ea-4a1d20f9d00c.png)

Cheers!

**Comment by harryray33** [comment]
Thank you, what I meant was, can I add some of the engines I have into the add group section?

**Comment by CanisLupus** [comment]
Ah sorry I misunderstood. I actually forgot that this was a problem so it didn't cross my mind that that's what you meant. :)

Unfortunately SSS doesn't support adding engines imported from Firefox to groups because they can only open in "this tab" or "new tab" (browser API limitations). If it did, it would break the way all other engines in the group open, depending on your settings (i.e. they would get weird order and focus would go to the wrong one when you open the group).

You might be able to create your own engines that mimic the ones you have in Firefox, but I fully understand if you don't want to go through that process, especially if you have a lot of them.

**Comment by harryray33** [comment]
Thanks, yes, I have quite a few engines...It's a shame about not being able to do this as the multi search is very useful. How would I go about creating engines in groups? I can't see a way to do this?

**Comment by CanisLupus** [comment]
You would first create any custom engines you'd like using the "Add engine" button, and then add them to a (new or existing) group. Also, to figure out how some sites work, please take a look at "I don't know how to add a particular site..." in the instructions. (Many sites are simple enough, but not all of them.)

**Comment by harryray33** [comment]
Yes, no problem about adding the engines, I was talking about the ability to include them in the add group section for a multi search.
Agreed about some sites make it simple, my favourite way, and the quickest, is to right click in a search box. I don't think I can do that with this, is tat correct or am I missing something?

**Comment by CanisLupus** [comment]
> the problem is that the search url doesn't show up for my existing engines ([Browser] Engine imported from the browser)

Yes, sadly the WebExtensions API doesn't let extensions see the URL of the browser engines, or any parameters. :(

> Agreed about some sites make it simple, my favourite way, and the quickest, is to right click in a search box. I don't think I can do that with this, is tat correct or am I missing something?

You are correct. If I'm not mistaken, something like that would require the extension to recognize the way each website does their search, and there's no generic way.

I really wish the WebExt API would let us see the search engine URLs and parameters.
