### ISSUE TITLE
Improve accessing SSS' settings

### ISSUE THREAD

**Issue by Canowyrms** [CanisLupus/swift-selection-search#243]
Accessing SSS settings is unintuitive and obscure (at least on Firefox and Firefox Developer Edition on Windows 10).

I was about to file a bug report about being unable to access SSS' settings because I couldn't figure out where to go, how to open them, how to get back to the config page. By a stroke of luck, I figured it out.

Most every browser extension I've ever used provides an icon in the extensions area (or in the extension overflow area) of the browser window. SSS does not provide such an icon. It is not documented anywhere how to access SSS' settings after the initial setup (right after installing/activating the extension) (if it is documented, I was unable to find it after a few minutes of searching on Google).

It turns out, to access SSS' settings, you need to go to your browser's extensions manager, click the menu button (three little dots), then click the options item. I've never accessed an extension's settings this way; I didn't know it was possible. I'm usually able to go through the extension icon to get to an extension's config.

Please add documentation on how to get to SSS' settings, or set up an extension icon in the browser's extensions area.

Keywords: access swift selection search settings

**Comment by CanisLupus** [comment]
Hi there! Sorry for the late reply!

Yes, I can see how it is unintuitive, sadly. It was actually not this bad a few years back, but Firefox made the options pages for addons very hidden some time ago, so now you have to go through some hoops to find it. 😕 I had never gotten this feedback so I guess I never thought much about this. Thanks for bringing it to my attention.

As an important note, SSS is not currently being developed, apart from severe bugs that may show up. But documentation could be a simple thing to add. When you mention documentation, where would you go to find it, as a user? SSS's page on addons.mozilla.org?

Adding an icon would definitely work and probably be clearer, but its ONLY purpose would be to access the options menu, which I'm not convinced is the best use for an extension icon (though you could always disable it if needed). It's also a new feature, which I'd like to avoid if alternatives are possible. :)

What do you think?

Cheers!

**Comment by Canowyrms** [comment]
Hey, thanks for getting back to me!

I'm not experienced at all in browser extension development but I have heard the odd gripe here and there about how things have changed in recent history, and how things like this are a bit more complex.

I think an intuitive place to look would be the extension's description right in the browser's extension management area. I think next up would be the extension's page in the extension directory (i.e. addons.mozilla.org). I'm not sure how many users would end up here on GitHub but maybe a quick commit to update the readme wouldn't hurt? Perhaps I could find a few minutes and submit a PR for that.

I'm on the fence about the icon, personally. If implementing it is a bunch of work, maybe it's not worth it. On the other hand, an icon reminds users the extension is still installed/active. To keep a clean interface, the icon can simply be tucked away in the extension menu (Firefox has an 'Overflow menu' for extensions and other toolbar items). It'd be nice to have, but I understand the extension is no longer under active development, so it's really no big deal.

Cheers 🙂

**Comment by CanisLupus** [comment]
Hi again and thanks for the extra feedback. :)

> I'm not experienced at all in browser extension development but I have heard the odd gripe here and there about how things have changed in recent history, and how things like this are a bit more complex.

Yes, some things changed for the better, others for the worse. The main change happened with the move of addons to WebExtensions, which invalidated all other addons at the time (and almost invalidated SSS because I really didn't want to rewrite everything from scratch, but I powered through 😅).

> I think an intuitive place to look would be the extension's description right in the browser's extension management area. I think next up would be the extension's page in the extension directory (i.e. addons.mozilla.org). I'm not sure how many users would end up here on GitHub but maybe a quick commit to update the readme wouldn't hurt? Perhaps I could find a few minutes and submit a PR for that.

Nice feedback! I've updated the addon page [here](https://addons.mozilla.org/firefox/addon/swift-selection-search/) to describe how to access the options menu. I hope it's clear enough. What's your opinion?

I want to avoid a lot of text since the description is already rather long. This description is also exactly what is shown in the addon details in Firefox's Extensions menu, so I guess it covers all of that. :) I think you are right that users will check there first and not GitHub (which is more developer-oriented) so I think we can leave that out.

> I'm on the fence about the icon, personally. If implementing it is a bunch of work, maybe it's not worth it. On the other hand, an icon reminds users the extension is still installed/active. To keep a clean interface, the icon can simply be tucked away in the extension menu (Firefox has an 'Overflow menu' for extensions and other toolbar items). It'd be nice to have, but I understand the extension is no longer under active development, so it's really no big deal.

I agree with all of this, and it's probably not even that much work, but I'd rather avoid it unless it's absolutely necessary.

Cheers!

**Comment by CanisLupus** [comment]
Fully agree with @Gitoffthelawn on this UI/UX issue. I didn't like it at all when they changed it, but it didn't occur to me that I should help clarify how to access the Options menu _because_ of that 😅

**Comment by Canowyrms** [comment]
> Nice feedback! I've updated the addon page [here](https://addons.mozilla.org/firefox/addon/swift-selection-search/) to describe how to access the options menu. I hope it's clear enough. What's your opinion?

Yeah, looks good. I think it'll suffice. Thank you for addressing that! Greatly appreciated.
