### ISSUE TITLE
[question] Is it possible to have several simultaneous searches?

### ISSUE THREAD

**Issue by IvoAndonov** [CanisLupus/swift-selection-search#247]
I can see that development is on leave, so my question is about the current version of SSS, which is one my most favorite extensions. Currently a search can be done only for a single site. But I wonder - can I have simultaneous searches with the same terms for all of them? To explain it better, it could be something along the line of "{searchTerms} selection ==> site1|site2|site3|site4|site5. Basically such a search would send {searchTerms} to all the 5 sites simultaneously and open all of the 5 different tabs for each.

Can such a search be done?

**Comment by CanisLupus** [comment]
Hi Ivo! If I got this right, yes you can. :) In the engines list you have this button to "Add group":

![image](https://user-images.githubusercontent.com/532708/159162833-14fca211-0a34-4357-a7d5-21a22eb4f3e3.png)

If you create a group, it behaves (as far as it can) as a single search engine that searches all the sites in the group simultaneously. This way you can keep your single engines as normal but also have groups for those special searches (and you can disable showing any single engine using the visibility checkboxes on the right if you JUST want to use it in groups).

Does this help?

Cheers!
Daniel

**Comment by IvoAndonov** [comment]
Yup, that's exactly what I needed. Thanks! :D
