### ISSUE TITLE
It's not possible to add new search engines from  "mycroftproject.com"

### ISSUE THREAD

**Issue by rodines** [CanisLupus/swift-selection-search#253]
Is any possible to add a search engine from "[mycroftproject.com](http://mycroftproject.com/)" direct to Swift-Selection-Search. Same Add-ons have  little icon near search engine links. You can add any engines with just a click.
Some one with the same Issue there?

![Polish_20220929_150128478](https://user-images.githubusercontent.com/79525897/193044616-45551da4-05df-43bc-89f6-e772aa91d142.png)
![Polish_20220929_145918482](https://user-images.githubusercontent.com/79525897/193044647-2160c6e0-ac0d-41ed-883d-e529e2e8e57b.png)
Do you have any idea to import the whole of search engines from Selection Search to Swift-Selection-Search at once?

**Comment by CanisLupus** [comment]
Hello there!

No, not directly at least. I'm not sure what those other add-ons that you mentioned do. Maybe they can parse these special search engines directly, but SSS doesn't do that.

What it can do, besides letting you create your search engines, is use Firefox's search engines directly. So if you add the engines from this website to Firefox, you can then import them to SSS using SSS's options menu:

![image](https://user-images.githubusercontent.com/532708/193118498-ce41f33e-3678-400d-8730-c9632ccd2e30.png)

As the description says, they are more limited than custom ones you create yourself in SSS. I don't know if the limitations are a problem for your usage, though.

I hope this helps (even if it really doesn't 😅).
Daniel

**Comment by rodines** [comment]
Thank you. I should have asked earlier. Because I thought I saw such a possibility with your add-on, which I unintentionally disabled. I even wanted to flatten my Windows because of it.

**Comment by CanisLupus** [comment]
You're welcome :) I'm going to close the issue but feel free to post here if you still have questions about this.
