### ISSUE TITLE
Strip spaces when using "Open text as link" option

### ISSUE THREAD

**Issue by Gitoffthelawn** [CanisLupus/swift-selection-search#31]
Hello! :)

When *"Show icon to open text as link"* is enabled and is used, strip leading and trailing whitespace (spaces/tabs/cr/lf) from the string.

**Comment by CanisLupus** [comment]
Hello there! :)

Ooooh, that seems obvious in retrospective. Duly noted! :)

**Comment by Gitoffthelawn** [comment]
Thanks!

**Comment by CanisLupus** [comment]
This was left here a long while for such a simple thing!

In the new version, 3.0.0, I simply do `searchText = searchText.trim();` before calling openUrl on the "open as link" icon, so I believe this is fixed. Please tell me if it isn't!

That said, the "open as link" might need a few changes to avoid trying to open a "ghost" resource link when used on normal text. That's another issue, though. ;)

**Comment by Gitoffthelawn** [comment]
Great!
