### ISSUE TITLE
Add seperators

### ISSUE THREAD

**Issue by aa3993** [CanisLupus/swift-selection-search#32]
New feature request: adding seperators between search icons.

**Comment by CanisLupus** [comment]
Apologies for only replying to you now. I will consider every request, including this and #33, and see if they should be added to SSS at a later time. Thank you for the suggestions. :)

Unfortunately, issue #24 will have to be prioritized above all others, as my time is limited and it is the only one that will definitely make SSS stop working if I don't deal with it.

Cheers!
Daniel

**Comment by Taurean75** [comment]
The separator icon is too wide! It'd be narrower than other favicons.

**Comment by Taurean75** [comment]
@CanisLupus It's perfect! 👍

**Comment by CanisLupus** [comment]
Hey @Taurean75, thanks for letting me know! :) Glad you like it! ;)

(For other people reading, version 3.21.0 adds an option for the separator width, as a percentage of the icon size. I set it to 60% by default, which is nicer than the previous implicit 100%.)

I'll close this now!
