### ISSUE TITLE
Context Menu shows disabled engines

### ISSUE THREAD

**Issue by T-Halen** [CanisLupus/swift-selection-search#38]
I have several disabled search engines (that can't be deleted), and they show up in the right-click context menu. They are unchecked in the addon settings, and don't display in the popup when a word is highlighted.  Only an issue in the context menu.  Thanks.

**Comment by jdreesen** [comment]
What's your setting for `Context menu engines filter`? When I select `all` (the default) it shows **all** search engines (disabled or not) in the context menu. When I select `same as popup` instead, only the enabled ones appear (like in the popup).

**Comment by T-Halen** [comment]
Yep, that was it, my mistake (doh!).  (Non-)Issue resolved.  Sorry.

**Comment by CanisLupus** [comment]
No problem! Thanks for the aid, @jdreesen. :)

Maybe the default should be to use the same engines as the popup, and not all of them...? What do you think?

**Comment by jdreesen** [comment]
> Maybe the default should be to use the same engines as the popup, and not all of them...? 

Yes, I think this would be less confusing and would correspond to what I expect. 
Especially because you **have** to use the context menu sometimes (because the popup doesn't work in textareas, for example) and it's a bit strange if there are other search engines you don't expect.

**Comment by T-Halen** [comment]
I agree on the changing of the default, but then again, my opinion is a bit biased. :)  Thanks.

**Comment by CanisLupus** [comment]
Thank you both for the feedback. :) I agree with you, it seems more reasonable. jdreesen raises good points as well. I'll look into the editable text fields issue eventually.

I've changed the default in 3.2.0. It won't change for existing users; only for new ones, in case people were relying on the default.
