### ISSUE TITLE
Show icons in the context menu

### ISSUE THREAD

**Issue by jdreesen** [CanisLupus/swift-selection-search#39]
It would be awesome if the icons of the configured search engines would be shown in the SSS context sub-menu.
This would make selecting the desired one much faster.

**Comment by CanisLupus** [comment]
Last time I checked, WebExtensions on Firefox couldn't add icons to the context menu, but that was a few months ago. Maybe it changed...? I'll see that when I can. :)

**Comment by hdd60311** [comment]
just look at some other context search addon and all of them can show icons in the context menu.
https://addons.mozilla.org/en-US/firefox/addon/contextual-search/
https://addons.mozilla.org/en-US/firefox/addon/context-search-we/
https://addons.mozilla.org/en-US/firefox/addon/selection-context-search/

**Comment by CanisLupus** [comment]
Thanks @hdd60311, that seems to prove that it works fine. ;) I'll try fixing this soon.
