### ISSUE TITLE
Importing from search.json.mozlz4 imports incorrect URLs

### ISSUE THREAD

**Issue by Gitoffthelawn** [CanisLupus/swift-selection-search#40]
When importing search engines from search.json.mozlz4, SSS is importing the *autocomplete* engine URLs instead of the actual search engines URLs.

**Comment by CanisLupus** [comment]
"Mom, I don't know how to Firefox!"

Thank you for bringing this to my attention! :) I've fixed it in the just-submitted 3.2.0 version of SSS (you'll have to reimport the engines file).

**Comment by Gitoffthelawn** [comment]
You're welcome.  And thank YOU! 👍
