### ISSUE TITLE
[Request] Change title of context menu to say something like "Search <selection> with..."

### ISSUE THREAD

**Issue by FatOrangutan** [CanisLupus/swift-selection-search#46]
The submenu of the add-on currently uses the name of the add-on as the title. Other add-ons like [Context Search WebExtension](https://addons.mozilla.org/en-US/firefox/addon/context-search-we/), [Selection Context Search](https://addons.mozilla.org/en-US/firefox/addon/selection-context-search/) show a more generic text e.g. `Search <selection text> with...`

I think it would be great if SSS could do the same. Looks like [this is how it is done](https://github.com/NumeriusNegidius/Context-Search/blob/f0be0e0b7c1dde591b1969204fc35113453a50a9/background.js#L97).

**Comment by CanisLupus** [comment]
Hello there! Thank you for the suggestion and the helpful link. Didn't know of the %s modifier (its usage is really specific, I must say!). I'll add this later as it seems simple enough. :)

**Comment by CanisLupus** [comment]
I've just added this in SSS version 3.5.0, which is now in review and should soon be available. Cheers! :)

**Comment by FatOrangutan** [comment]
Thanks for the quick fix! :)

[Bug 1370228](https://bugzilla.mozilla.org/show_bug.cgi?id=1370228) will fix the minor issue of context menu showing ellipsis even when the selection text is small enough to not overflow.

**Comment by CanisLupus** [comment]
You're welcome! ;) Yup, I noticed those extra ellipsis, but it seems that whoever was going to do the fix didn't respond anymore... I'll try asking too.
