### ISSUE TITLE
When selecting text in input fields, popup appears at the input field's corner instead of the selection's

### ISSUE THREAD

**Issue by CanisLupus** [CanisLupus/swift-selection-search#51]
When "Allow popup on editable fields" is on and "Popup location" is set to the selection rectangle, selections in input fields cause the popup to appear in the lower right corner of the input field instead of the lower right corner of the selection itself.

Unfortunately, I couldn't find a way to get the bounds of the selection inside an input field in JavaScript, like I do with non-input selections. Normally, the selection object gives me the bounds, but for input fields there doesn't seem to be one, so I defaulted the position to the bottom right corner of the input field itself.

I'll gladly accept any insight on this!

**Comment by Teko101** [comment]
Thanks a lot Daniel for your work, I really appreciate it.

As much as I'd love to help out, I'm no JS dev. You might want to check out this legacy addon which still works correctly (popup menu appears inside/outside the input fields based on cursor position):
https://addons.mozilla.org/en-US/firefox/addon/selected-search/
https://github.com/edawn/selected-search-firefox-addon

About Issue 35:
Whenever you decide to investigate "Current Site Search" Issue, I also suggest checking this addon out as a start:
https://addons.mozilla.org/en-US/firefox/addon/contextual-search/
https://github.com/odebroqueville/contextSearch/blob/master/background.js
Currently, it supports searching the active-site using only Google (that's enough for me btw) but may be if you intend to add multiple search engines (like: google, bing, yahoo, yandex... etc) by default to search the active site, I think it would be better to use something like a "wildcard" instead.
I mean adding search engines manually.
For example:
https://www.google.com/search?q={searchTerms} Site:{Wildcard}
Note that: "Wildcard=Active-Site" and same thing goes with other search engines of course.

As I told you I'm not a FF dev, so if I'm mistaken about anything, please forgive my lack of knowledge.

Hope this helps :)
Best Regards

**Comment by CanisLupus** [comment]
No problem! I appreciate the help, @Teko101. :)

I believe the Selected Search add-on always uses the mouse position to place the popup. I do that by default as well. But this issue only happens if the "Popup location" setting is set to the selection rectangle instead of "At cursor location" (mouse). You have changed this setting to the selection rectangle, correct? I never asked, but I assumed it was so. If not, something is very wrong! :)

If I try to respect the selection rectangle, I need the input field to give me a selection object, from which I can get the bottom right corner position, but they don't. :\ I can solve this by using the mouse position anyway for input fields, even if the user wants the selection corner, but I wanted a more graceful solution before resorting to that.

Issue #35 will involve a currently unknown amount of work since I haven't had the time to look into it yet. ;) Thanks for the examples! Just like you correctly suggested, it will indeed likely involve adding a new {currentWebsite} variable that you can use in the search URL for engines, so that SSS can replace {currentWebsite} with the website you're on.

Cheers! :)
Daniel

**Comment by Teko101** [comment]
> I believe the Selected Search add-on always uses the mouse position to place the popup. I do that by default as well. But this issue only happens if the "Popup location" setting is set to the selection rectangle instead of "At cursor location" (mouse). You have changed this setting to the selection rectangle, correct? I never asked, but I assumed it was so. If not, something is very wrong! :)

This is entirely correct. 
I changed the "Popup location" setting to "At cursor location" and everything is perfect now. Thanks :)

About Issue 35, please take your time, you're already doing a great job.

Cheers!

**Comment by CanisLupus** [comment]
Thank you for your kind words! :) OK, great, I'll see what to do about this issue eventually. It's a relatively minor one, thankfully. ;)

**Comment by CanisLupus** [comment]
Although this was never solved, I think that very few people use something other than the "At cursor location" option, and fewer still will have that AND the popup enabled for editable text. Furthermore, I also don't have a solution that doesn't involve creating fake temporary text elements in the DOM and some very hackish code, so I think I'll simply mark this as "won't fix" and close the issue.

It's also a minor problem that got no complaints in 3 years, so... :)

If someone is reading this and finds this very annoying, please comment here, but I can't promise anything. The solution in JavaScript is really bad and I'm unsure if some site's content policies wouldn't cause problems anyway.

Cheers!
