### ISSUE TITLE
Suggestion: Auto paste of copied fragment behavior on mouse right-click

### ISSUE THREAD

**Issue by VDegest** [CanisLupus/swift-selection-search#57]
Hi Daniel,

your add-on is awesome and it made my searching experience more fast. There is one feature that I really miss, could you add an auto paste behavior of copied fragment behavior on mouse right-click? I would appreciate that.

Thanks for attention :)

**Comment by CanisLupus** [comment]
Hi, and thank you! Sorry for the delay. Let me understand the suggestion first. :) After clicking the copy icon (or perhaps if you have "Auto copy to clipboard" on) you would like a way to paste the copied text by right clicking, perhaps on an input textbox? If this is correct, it may be a problem. ;)

Is there anything you don't like about right clicking and then selecting "Paste" from the context menu? I may not be able to avoid showing the browser's context menu when you right click on the page. I'm not sure if extensions can do that.

Cheers!
Daniel

**Comment by VDegest** [comment]
Hi Daniel, thanks for replying.

"After clicking the copy icon (or perhaps if you have "Auto copy to clipboard" on) you would like a way to paste the copied text by right clicking, perhaps on an input textbox?"

Yep, totally 100% correct :)

"Is there anything you don't like about right clicking and then selecting "Paste" from the context menu?" 

It is annoying and time-wasting :)

"If this is correct, it may be a problem. ;)  I may not be able to avoid showing the browser's context menu when you right click on the page. I'm not sure if extensions can do that."

I suggested this feature, because I was using it successfully in similar to yours extenstion (don`t recall it name, stopped maintaning about 2 years ago :/). That why, I thought it was possible to implement auto paste feature in Swift Selection Search. Maybe, Mozilla changed something in Firefox in recent years, that now do not allow developers of extentions to make auto paste feature on right click possible.

**Comment by CanisLupus** [comment]
OK, I see. :) I'll check it out when I can and see if it's possible. WebExtensions are a bit of a pain sometimes! ;)

Cheers!

**Comment by markran** [comment]
@VDegest You can have the functionality you are requesting above by using a mouse macro software on a multi-button mouse. I use the software that came with my Logitech mouse to assign Paste (CTRL-V) to a button and it can be conditional for when the mouse is over Firefox if desired. Such software has many options such as pasting on long-press, double-click, two buttons at once etc. 

It's actually much more flexible than adding it to SSS because you can have it work in other programs.

**Comment by ZIEXED** [comment]
Firefox > about:config > Set middlemouse.paste to "true"
much more convenient

**Comment by VDegest** [comment]
Hi, yeah, it is working as requested, I use this feature every day. Many thanks for implementation.
I am closing this issue now.
Cheers!
