### ISSUE TITLE
Open In New Tab

### ISSUE THREAD

**Issue by mkrehel** [CanisLupus/swift-selection-search#63]
Hello,

Not really an issue, but a request.  Your Firefox addon is great, but would be even better if there would be an option to "Open In A New Tab".

Thank you,
Mike

**Comment by ZIEXED** [comment]
![1](https://user-images.githubusercontent.com/14824755/34327875-cb7a5a1e-e8d8-11e7-8e1d-6647aacb3459.png)

**Comment by mkrehel** [comment]
I somehow missed this.  Thank you for your help.

**Comment by CanisLupus** [comment]
Hi @mkrehel, Sorry for being late! The holidays! :)

Thanks a lot for the assistance, @ZIEXED ;) I'm glad everything was sorted out.

- Daniel
