### ISSUE TITLE
permissions!

### ISSUE THREAD

**Issue by rezpower** [CanisLupus/swift-selection-search#69]
Hi there,
I am using this extension with great joy and it has become my favorite. I am sure it's a safe extension, but for more transparency and information could you please explain the reason for latest permission need on last update?

**Comment by CanisLupus** [comment]
Hi rezpower!

I fully understand your concern. The new permission, which is called "webNavigation" was required to fix an issue where SSS wasn't able to register with individual frames in a page, especially if those frames were only loaded after the main page (see issue #56).

Unfortunately, given the APIs I can use, registering with the page load events (which are also triggered for individual frames) was the only option I could find to fix it, and that requires the webNavigation permission.

It was suggested in an answer to my question [here](https://stackoverflow.com/questions/47593407/how-to-executescript-on-all-frames-of-a-page-as-they-load-i-e-not-using-docume).

It is only used for that purpose, although I'm sad that I have to request it just for that. It was also the case with the "downloads" permission a few months back, which was also a bit ridiculous and used for a single purpose that I wouldn't even call a download. :(

I had briefly noted what the change was in the release notes for version 3.12.0, which are visible in [SSS's page on Mozilla Add-ons](https://addons.mozilla.org/firefox/addon/swift-selection-search/): "Fixed popup not appearing in most pages that use frames (the solution requires a new permission for “webNavigation”)." I will also note it down in the main SSS description, in case people look there. :)

Cheers!
Daniel

**Comment by CanisLupus** [comment]
Thank you for your kindness. :) I'm glad I could explain, as I surely don't want anyone concerned about the permission. I suppose a lot of people found it strange as well. If this happens again I'll be sure to put it up on the main description as well. ;)
