### ISSUE TITLE
SSS doesn't work in multiprocess Firefox

### ISSUE THREAD

**Issue by CanisLupus** [CanisLupus/swift-selection-search#7]
As some of the SDK is incompatible with multiprocess Firefox, the event that triggers on text selection supposedly fails without the SDK's adapters (called shims). This would be okay, since the adapters seem to be usable. See [this link](https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Multiprocess_Firefox_and_the_SDK#SDK_internal_incompatibilities) for Mozilla's (short) details.

However, trying to `require("sdk/selection")` (just trying Mozilla's example from the link above) throws this error:
`TypeError: window.getSelection is not a function`

This happens with shims on. If multiprocess mode is on, shims are off and I get a `TypeError: window is null`, but this is probably expected. Shims failing is not.

**Comment by CanisLupus** [comment]
Firefox bug documented here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1182618

**Comment by CanisLupus** [comment]
Fixed in 2.24.0 by fully replacing usage of Firefox's text selection module (which had bugs in multiprocess) by a custom text selection module that works per-page instead of globally. Some code had to be changed or moved. The behavior for text selection might not be _exactly_ as before, but should be close enough that the change shouldn't be noticeable.

**Comment by OdinGitDat** [comment]
thank you! been waiting to use sss in my e10s ff
