### ISSUE TITLE
Since Firefox 58, SSS doesn't work?

### ISSUE THREAD

**Issue by pedrom34** [CanisLupus/swift-selection-search#70]
Hi,

Since Firefox 58, popup shows, but clicking on icons doesn't work... Like nothing happens.

Is it a known issue ?

**Comment by jdreesen** [comment]
It works for me on Win 7 with FF 58.

**Comment by T-Halen** [comment]
Same for me in 57.0.4
Popup looks fine, but nothing works.  Context menu doesn't work either.
Maybe 3.13.1 broke something?  Is there an easy way to roll back?

**Comment by CanisLupus** [comment]
I woke up to quite a few reviews and emails mentioning this but I was at work until now. :O Firefox 58 is fine, but my last update introduced a bug that caused the first 3 "opening behaviours" to completely fail.

Fault's on me! I submitted a fix just now (v3.13.2), I hope everything is okay now. Apologies for the inconvenience! :s

Daniel

**Comment by Gitoffthelawn** [comment]
New release is working for me.  Thanks Daniel!

**Comment by CanisLupus** [comment]
Thanks for confirming, Gitoffthelawn! :) Sometimes really dumb mistakes are made, and this time it was my mistake (after fixing issue #67 I didn't check the other SSS opening behaviours and they were using an undefined variable *sigh*).

Thanks everyone for reporting!
