### ISSUE TITLE
Seems not to work in DeepL

### ISSUE THREAD

**Issue by a3overgaauw** [CanisLupus/swift-selection-search#73]
This gives an empty pop-up: https://www.deepl.com/translator?q={searchTerms}
But maybe I just can't find the right syntaxis.

**Comment by CanisLupus** [comment]
Hi a3overgaauw!

Sorry but this depends on the website itself. That site doesn't seem to accept a text query through a URL, or, if they do, they don't seem to show how. q={searchTerms} works for Google, but each site uses its own method.

Usually, if you write text on an input field (text box) in a website and URL doesn't change, you don't have a way to add it to SSS. Adding support for some of these sites (those that use POST requests) is in my plans, but this one might use something else, like Ajax.

Daniel

**Comment by a3overgaauw** [comment]
Dear Daniel,
Thanks for your answer. I continue to like your add-on a lot.

**Comment by CanisLupus** [comment]
Thank you for using it. :) Sorry that I couldn't help!

**Comment by LegitLlama** [comment]
Just to leave a trace for the future (at least until DeepL changes), it is possible to use DeepL with SSS using the engine ```https://www.deepl.com/Translator#en/fr/{searchTerms}```. This will assume the text to translate is in English by default, but DeepL detects the language so it works for any language supported by their service. The text will, in this case, be translated to French.

**Comment by CanisLupus** [comment]
Thanks @LegitLlama! I'm pretty sure that at the time it was only POST, or at least it didn't clearly show a way to do it in the URL. I can see that's better now. ;)
