### ISSUE TITLE
Not all entries in search folder appear

### ISSUE THREAD

**Issue by danneauxs** [CanisLupus/swift-selection-search#74]
when I load the browser search engines from the selected file (search.json.mozlz4) not all of the search engines appear just some of them. I can manually add them but not sure how to add the icon.

**Comment by CanisLupus** [comment]
Hi there! Can you send me the search.json.mozlz4 file so I can check what's happening? Feel free to tell me "no, thanks" if the search engines are personal, that's okay!

If you can, please send it to daniel.rb.lobo+sss@gmail.com. If you'd rather not, please give me more details about what's happening. Which search engines are not being imported?

Usually, to add an icon you search the web for an image (preferably square) and add the image URL as the icon in SSS. :) SSS will resize the image to icon size internally. It can be a png, jpg, ico, etc.

Daniel

**Comment by ZIEXED** [comment]
https://besticon-demo.herokuapp.com
