### ISSUE TITLE
Reverse order; Delay for popup

### ISSUE THREAD

**Issue by Gnustier** [CanisLupus/swift-selection-search#76]
Could you please, 

- Make ability to reverse order the search engines when display the popup.
  Works only in popup, not in the settings page.

- Make ability to delay the popup after selection, and make the delay time could be customized.
  In order to prevent accidentally click the popup when the triple click is not finish yet

- Improve the visibility of settings page when the theme of OS is not bright. 
  [settings-page--screenshot](https://user-images.githubusercontent.com/34122232/37608528-c42dc5d0-2bd5-11e8-8b37-d91cf9324a0e.png)

**Comment by Gnustier** [comment]
I close this issue and separate content into different issues.

**Comment by CanisLupus** [comment]
Hi there @Gnustier!

I see you haven't posted this as separate issues yet. Please note that the second one is already covered in issue #68. :)

The third one is.... well, something I didn't expect :p Maybe setting all the colors by hand would fix this. Could you tell me what you are using exactly to get these colors?

Lastly, about the first issue, what is the use-case for this? Just an icon reading order preference, similar to how some languages read right-to-left?

Cheers,
Daniel
