### ISSUE TITLE
Missing search engines in popup

### ISSUE THREAD

**Issue by T-Halen** [CanisLupus/swift-selection-search#77]
I have 7 search engines in my popup, plus the 'Copy' icon.  But when selecting text on the below page, I can only see one icon, the first one.  All others are missing.
http://articles.latimes.com/2006/nov/27/sports/sp-adande27

Otherwise, this addon has been working great, and I love it, thanks!

**Comment by T-Halen** [comment]
Thanks for investigating.  I don't consider this a high priority issue, unless others come across similar sites.  Keep up the fantastic work!

**Comment by T-Halen** [comment]
Looks good from here - thanks!!

**Comment by CanisLupus** [comment]
Great! :)
