### ISSUE TITLE
Doesn't open new tab in firefox

### ISSUE THREAD

**Issue by chimerical26** [CanisLupus/swift-selection-search#83]
Subject says it all really. Maybe I'm doing something wrong but when I click a search engine it opens in the same window irrespective of what options I have selected.

**Comment by CanisLupus** [comment]
Hey chimerical26, can you tell me if you managed to solve the problem? :)

**Comment by RafaelSTA** [comment]
I had the same problem and it worked for me, thanks :)
Your extension is great!

**Comment by CanisLupus** [comment]
Hi Rafael, glad I could help. ;) And thank you :)
