### ISSUE TITLE
Search engine icon visible in the browser, invisible in the pop-up and at settings/settings.html

### ISSUE THREAD

**Issue by grahamperrin** [CanisLupus/swift-selection-search#98]
From [Not all icons show at Hacker News / ycombinator.com in Waterfox · Issue #92 · CanisLupus/swift-selection-search](https://github.com/CanisLupus/swift-selection-search/issues/92): 

> …  all sites now, …

1. In a pop-up, observe the absence of an icon
2. moz-extension://e55ebe97-d071-4cb5-a65a-cd6b3c22ccf3/settings/settings.html
3. observe any corresponding gap

## Example

With the listings for [Findx](https://addons.mozilla.org/addon/findx/) and two others affected in Waterfox 56.2.0.19 on FreeBSD-CURRENT: 

![2018-05-30 07 07 04](https://user-images.githubusercontent.com/192271/40702684-af14ae92-63da-11e8-9fe3-e41d93508357.png)

![2018-05-30 07 07 48](https://user-images.githubusercontent.com/192271/40702728-d2d5c708-63da-11e8-8369-acac45d033ab.png)

### Observations

Screen recording available on request. 

At first I thought I had a reliable workaround, at least for Findx, involving: 

1. visit resource://search-plugins/images/findx.ico
2. reload without cache e.g. <kbd>Control</kbd>-<kbd>F5</kbd>

Then I realised, something **session- or cache-related** may cause the issue to be temporarily non-apparent. More specifically: 

- close a tab
- History menu ▶ Recently closed tabs ▶ reopen the tab
- use Swift Selection Search, observe the required icon

– three frames from the screen recording: 

![2018-05-30 07 33 52 frame](https://user-images.githubusercontent.com/192271/40703599-915f9a94-63dd-11e8-9551-8cc351e9e310.png)

![2018-05-30 07 33 54 frame](https://user-images.githubusercontent.com/192271/40703611-9885b402-63dd-11e8-9dd2-508d34c3f4d6.png)

![2018-05-30 07 34 02 frame](https://user-images.githubusercontent.com/192271/40703618-9f627ada-63dd-11e8-9bcc-4a615328eee0.png)

**Comment by grahamperrin** [comment]
On closer inspection, the Findx example is probably an issue with Findx, not with Swift Selection Search. Cross reference to follow. Apologies for the noise …

**Comment by grahamperrin** [comment]
## Workaround

### tl;dr 

1. [Extension source viewer](https://addons.mozilla.org/addon/crxviewer/) to the rescue
2. visit the addons.mozilla.org page of an affected search engine
3. use Extension source viewer to show images 
4. identify the most suitable image
5. image ▶ context menu ▶ Copy image location
6. moz-extension://e55ebe97-d071-4cb5-a65a-cd6b3c22ccf3/settings/settings.html
7. paste the location of the image to the appropriate field in preferences for Swift Selection Search.

**Comment by grahamperrin** [comment]
## Workarounds: additional information for Findx

Edge case first: Findx. 

`resource://search-plugins/images/findx.ico` – the URL that is selected in the second screenshot in the opening post – is a mystery to me. I wondered whether it's a relic of the Findx add-on https://addons.mozilla.org/en-GB/firefox/addon/find-x/versions/ that is **not** developed by the developers of Findx … however so far, I do not have any evidence to support that guess. @brianschildt please, is `resource://search-plugins/images/findx.ico` familiar to you?

----

For the **proper** Findx extension by Privacore <https://addons.mozilla.org/addon/findx/>, version 1.0.11, the best URL for Swift Selection Search search engine icon purposes seems to be, at this time: 

- `images/findx_logo.png`
- not `images/logo.svg`

Specifically, here: 

`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAIAAABMXPacAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAACAtJREFUeNrsnU1MVFcUxxEoHwHH0Awh4cNajAZwMa6QtGGFUWpXGhBWbQK4h+K66l4+EpeKSbuiQGSlRaIr0xZdyQKHSAANjAlxomHAANPQ9D9MpFNmeO/c9+57794354SYiE98nt89/3PuvefeyT9+ZzaHzTvLZRcwAAbAxgAYABsDYABsDIABsDEABsDGABgAGwNgAGwMgAGwMQBfW76arxUozGsIFh8rzK0+WjAX3X4V3Yrt7DIAN6ypqrSvsaKpquTA92cin4ZerM1ENn0G4Ig6m/IY9QPnay58HTB45v5s9Nazd5wDHPH+2OWTxt6HdYWCU52nGYB8w9ivDxZRnsRjeJhzgExrry8zHfup1lZXNvIyiszs/qtWBwpQFxz4JgoEyy+jBABkXaHnIxvx1Y24C74+EyxCMdZQXhwoyEuvC9LLhOml9fH5j0IFW74Kw78qbUwZW8/Dtw5VpXD3xdoAKrEz5UVHC/IE67cSfPWdq0B0omDTBkB3qFzoeRRCcsUH+T/pdPwq6vR0w0/obaxA9PQ/WdEAAF6UmHuTthHfpQ8uU4PH2+q/FEo/9Cy1GotTXtVjABcF//OYBNgXH1DvDgUhffbHu1Fknw1qAKCpulRo+I+HP9oc8l2hctN0KsVAFxnFVC09BnBGRH+Q3OyketRaotnefnZRPQKEPIIKTxfXfy5MN5UGgAilPxyObiOt6eJ62ARtuHgJgBKh/w3/8AeRkrz0ZnOlUH0l1+jVmqL7Aen2V+QTscK50VzpRGUpZJgEEOPVSwBCGZgy+YLgoPhztLg0GPJz77c/TxXfP16KaTATpkvQjNnwRzoZJK+nWrbIRnwl9jdSK+Yic9FtYpr1gwQZL71h4PcKLufRPQ5Hz6xuJn51ZjNOEwCH6KlDA396OQanP16OidZdvgWQMQF0h4I/N1dKFHEI9/TSOl2+tQeAwqaX9uT6zj8Hkofp7rHQeJ8If3DZ7/qVoamyc+/7r+xPr6DvIy+jovsn2Q5AiuygphKqFH0LQHRbEbLTVldm0/WqNRd5CoBcYxwrzJ3qPG2n2lG2r8tjCYIQU9QcY9/y/FbxljqPAWBiSQFgzfugC9fb3MPxOQAU+A7tTw2/WBuZjarf0usxACemmtCc/qcrLkxi/QAguaQlcTY79Dwx8DUqrL2XoOwc+PvmcXMuNDosIwig+B2Ti9p5X4mZ8Fx0y06Bj1Kn5+FbTxp1/RABOfb2NCA7raML+npfiQggbvZmlB2JbYrZGwEQ7ojgohCqnetPV3zg/Rwd29Ph/asPlrSWHYUAXKwN3G4ROG+Ekunq5KKfjqx6KUENwWKh015QKp9530sA1YGCsSu1QqtsXjUZ+hBAoDDv3qUTFtY4IVkMQIINWO0luVB7jAHYtb7GCssNDfiLQi29DCCDhtjsYmu3ty2c1QCQeO0fcu8+G2QAFs1a4k2vhZqqShmAsN2Qd2LCT0HgEoC944nSvIZUDDVjAAJVP1H6N+K792kbin3O9KP7E8BdsvTfevYOX5TF0ba6Mn8EgeMAukNBYuMJxn6yh4fYyeOPIHAWAAZp3zmSm2Yin/bvIhuZjUKLsiQInAUw0EJqKYS7rz16s//b2M4u8VC8D4LAQQB7d8CQxCf9/h96EAid9s4iAPTKZzhT5yw9CG7IO6XkKwAQB4r4JFuXM/4RMQgQZO31ZQzgYO6lTLvg3/6nh14rhSAgXhGKINB3idQRAAO0bd6h52vGvWyoRylzAoSavtlYPoCmqlJK7oX4ULpof3qySvlHuxKzjVIGkLCbhKxoLD7/57Q5vUw6TTd4vlpHIZIMAPmQsuRpKj6p1v9khZKNq44W6ChEkgFQXBCObgu18CMbE6+AhBBpt2ufK3f4UzpHbopff564RIAmRJh86CVEMgFQrmCdmP9orR2aKESoiO5eOpGNAFCEkNTfakcthKjn4Vvam5RoND2WBoCyTTj8Ys3OIRaEDnG7pmvvXtYsAoCpr2mrDwTE/vE5zI1naOcJbrfUaLFOJwcApVdn5KWcU7vXHr0hnicYu1KrPgNJAMziXcrwT00GxIQ8qHxRJAEASm/T6lPW8E/aq+jW1QdLlCdRF4xdPqkyAwkATBtmJQ7/VAbXaYsZijOQEwHGD4yHHbmVCj/WBwzsAkCWM914ce7uAB8wyHV6+E87fPkjGHRMLlFycpKBanWRXQCmq/ATIpduW56gISdTGShWm9oHYLT3goLdnbvxkJO/+WWecu0EBPP3zlPqzJNtATAdSm7eVoU83zr6mrhWgXmyIuumtgDUBL4wATDv9nVht569Q0ogdpdOdZ7yfCPTwQiw8JkXslJC6+gCJRQwf/ztcq23TRW2ABi/97jz6ddAjhAK340uUFbuukLBP3+s8yorOBgBj5c9vpoWmbljchGKZIoBmRlZwRMMTnXGJT5vU437q6BIwPDtr/MQJePcAEVKYujb+yxCvQEocjPzvmE0QJRQqiIgQMKgYAWG3saKP36oc2e6kO/cuMtR0vBi+++W+NTUYBEyWfIDa1O1CwPInRtxbAEwuHbV8j1YXsHQsgo6bI0TUuuzS2UUBXDYMJd7HSsDEBb6V++32LMuVUEZPzFRiwTgEwAZl9s4AbgHIGP7uG+uNNRjIkbs2mRzCgAEJ3VDKswlkPtLEdCc1tGFpOvXOQF4shSxGou3jr5ury/z021KLtiR43dm2QvaSxAbA2AAbAyAAbAxAAbAxgAYABsDYABsJPtXgAEA1pfZImE7dRgAAAAASUVORK5CYII=`

**Comment by CanisLupus** [comment]
Hey @grahamperrin, thanks for the extremely detailed report!

SSS has problems using "resource" links for icons. I mention this in the Troubleshooting section of the options page:
> Some search engine icons may not appear if they are "resource://" links (some imported engines have those).

I have it pending to find a solution to this (if possible), but the fact is that it currently doesn't load icons from those links. All 3 of the invisible icons are "resource" links, unfortunately. Using png, jpgs or data: urls should work nicely, in the meantime. Sorry for the trouble!

Cheers,
Daniel

**Comment by grahamperrin** [comment]
Thanks! I saw the documentation, which is clear enough, after a while, but I wasn't entirely sure that it applied to all three cases here … partly because of the _apparently_ random nature of things; the `resource://` approach sometimes working, sometimes not. 

I don't see anything to action here so I'll close.

**Comment by CanisLupus** [comment]
Indeed, it working for a few frames before disappearing _is_ strange. I'm not sure how that happens and I hadn't noticed it before your report. I will try to look at it soon. It is especially annoying since imported engines sometimes have resource links for icons. Thanks for the help! :)

**Comment by grahamperrin** [comment]
> …  I will try to look at it soon. …

Honestly, don't trouble yourself unless the curiosity burns you. 

Session storage with Waterfox 56.x is in some ways a dog (for me, YMMV) – part of which might be current limitations of the inheritance from ~Firefox 56.0.2, part of which might be me pushing things hard with umpteen extensions and umpteen-tab sessions. That's not to point the finger at Waterfox project or Mozilla; it'll simply be some time before enhancements, fixes etc. can come together. A sprinkling: 

- [394492 - SessionStore API performance issues with large number of windows and tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=394492)
- [669034 - (sessionRestoreJank) [meta] Re-architect session restore to avoid periodic freezes](https://bugzilla.mozilla.org/show_bug.cgi?id=669034)
- [706970 - Tabs restored at startup (app tabs, session restore) should be refreshed from server, not in a "stale" state from cache](https://bugzilla.mozilla.org/show_bug.cgi?id=706970)
- [799862 - favicon bookmark icon is stale](https://bugzilla.mozilla.org/show_bug.cgi?id=799862)
- [810932 - Investigate how to redesign sessionstore.js for improved performance](https://bugzilla.mozilla.org/show_bug.cgi?id=810932)
- [874381 - [meta][SessionStore] Clean up and document session restore](https://bugzilla.mozilla.org/show_bug.cgi?id=874381)
- [1330635 - (ss-perf) Sessionstore performance tracking](https://bugzilla.mozilla.org/show_bug.cgi?id=1330635)

(Maybe also a dog with Firefox Quantum. 60 is simply nowhere near ready for me to draw a comparison.)

**Comment by CanisLupus** [comment]
I have never used Waterfox but I see why it would be behind in terms of features when compared to normal Firefox. :)

Nevertheless the resource links issue is something I wish to look at when possible, as it is not specific to the older versions but something that still happens and... shouldn't.
